### ISSUE TITLE
Insert-mode selection is cleared when pane opens

### ISSUE THREAD

**Issue by maxim** [NeoVintageous/NeoVintageous#1020]
**Description**

If you switch to insert mode, select text using e.g. shift+up/down, then open some kind of bottom pane, the selection clears. It shouldn't clear. This problem doesn't occur if NeoVintageous is disabled. It also doesn't occur when using visual selection mode.

Here's an example with opening OpenAI plugin's pane:

https://github.com/NeoVintageous/NeoVintageous/assets/7758/6a12ec9e-25ab-449f-8d14-2c1dc1ad9b71

**Steps to reproduce**

Steps to reproduce the behaviour:

1. Enter insert mode
2. Select text
3. Open any pane via command palette (i.e. build? not sure what panes Sublime has by default. I used OpenAI completion plugin as an example.)

**Expected behaviour**

Selected text stays selected in the editor.

**Actual behaviour**

Selection is cleared in the editor.

**Version**

```
startup, version: 4175 osx arm64 channel: dev
```

(This is not new, has been happening through many versions. I've never seen it work in the past.)

**Comment by gerardroche** [comment]
There are several settings that might get you the behaviour you need.


Check out `vintageous_reset_mode_when_switching_tabs`:

https://neovintageous.github.io/reference/settings#vintageous-reset-mode-when-switching-tabs

and `vintageous_default_mode`

https://neovintageous.github.io/reference/settings#vintageous-default-mode

Reworking the mode handling is long standing issue. It's difficult
because there are still some limitations in Sublime Text.

This is known issue: https://github.com/NeoVintageous/NeoVintageous/issues/834

But I think `vintageous_reset_mode_when_switching_tabs` might be the
workaround.

**Comment by maxim** [comment]
@gerardroche Appreciate the explanation. Setting `vintageous_reset_mode_when_switching_tabs` to `false` indeed fixed the issue for now. 👍🏻 Since there's a roadmap item already, I'll close this issue.
