### ISSUE TITLE
Updating vnoremap silences built in selections

### ISSUE THREAD

**Issue by itsmewes** [NeoVintageous/NeoVintageous#1034]
**Description**

I'm a PHP developer and wanted to add a text object so that I could visually select PHP functions. So I added the below to .neovintageousrc:
```
vnoremap af <C-[>?function<CR>^v<CR>%
vnoremap if <C-[>?function<CR><CR>viB
```

This worked well and selects the functions as I would like, but then the other selections have stopped working. For example if I were to try `va{` or `vi[` it would no longer select anything.

**Steps to reproduce**

Steps to reproduce the behaviour:

1. Add the above script to `.neovintageousrc` and reload.
2. Find a PHP file that has methods/functions in it and use `vif` and `vaf`, the functions should be selected.
3. Try run `vi[` or `vi{` in the respective place and nothing should happen.

**Expected behaviour**

Current visual selections should still work.

**Actual behaviour**

Nothing happens.

**Version**

To access the version view the console log:

**Menu → View → Show Console**

```
startup, version: 4183 osx arm64 channel: dev
```

**Additional Information**

This could be due to my implementation, but thought I would ask and see if there is a better way to do this. I have added the above `vnoremap` to my `.vimrc` and everything works as expected. I also tried it without `<C-[>` in case the `esc` was causing an issue but same result.

Thanks for all you do with NeoVintageous, I couldn't code without it!

**Comment by gerardroche** [comment]
It looks like multi key mappings shadow the first key prefix. In this case `i` and `a`. I was a little surprised these mappings worked at all. They are reasonably complex. 

In the meantime I can suggest using a mapleader. It's not ideal.

```vim
vnoremap <Leader>af <Esc>?function<CR>^v<CR>%
vnoremap <Leader>if <Esc>?function<CR><CR>viB
```

I'm noticing some small inconsistencies with vim: NeoVintageous adds an extra carriage return in some cases (e.g. after `function<CR>`). This matters when you want to also clear search highlighting. For example, in Vim this works:

```vim
vnoremap <Leader>af <Esc>?function<CR>:noh<CR>^v<CR>%
vnoremap <Leader>if <Esc>?function<CR>:noh<CR><CR>viB
```

But in NV the first one won't work because an extra carriage return is added. You can work around it by adding the `:noh` at the end (which won't actually work in Vim):

```vim
vnoremap <Leader>af <Esc>?function<CR>^v<CR>%:noh<CR>
```

**Comment by itsmewes** [comment]
Thanks for your detailed feedback. I currently have the  mappings set to:

```vim
vnoremap F <Esc>?function<CR>^v<CR>%
vnoremap f <Esc>?function<CR><CR>viB
```

which have been working for me. Just thought I would ask in case there was something else that I could do.

Thanks again.
