### ISSUE TITLE
YP yank then paste regression

### ISSUE THREAD

**Issue by gerardroche** [NeoVintageous/NeoVintageous#2]
//
    //|
    // 

From the above position where | is the cursor. `YP`

Expected

    //
    //
    //
    // 

Actual

```
    //
    /    //
/
    //
```

**Comment by gerardroche** [comment]
Had to revert [#1041](https://github.com/guillermooo/Vintageous/pull/1041): Fix for P newline pasting.

**Comment by craig-sh** [comment]
Hey,

Thanks for reviving this project!

Looks my changes lacked sufficient testing. I'd like work on it further... should I make a new issue for it or would you like to reopen this one?

**Comment by gerardroche** [comment]
Yeah, I had revert because I'm trying to get a release out the door. But yeah, I've reopened it. I've also ported all the issues from the other repository, here's the new ticket https://github.com/NeoVintageous/NeoVintageous/issues/224

Also I should note that while doing some testing on Windows recently I found that YP seems to be fine on Linux but is broken on Windows.

**Comment by craig-sh** [comment]
I've been looking a bit closer at the logic to paste from registers in NeoVintageous and typing `YP`:
```
a|bc
def
```
will yield the below text which lines up with VIM:
```
abc
abc
def
```

However, if the text (including the newline as mentioned in #224) is selected visually and yanked in vim with the key strokes `vely`
```
a|bc
def
```

And when pasted with `P`, we expect
```
abc
bc
def
```

but NeoVintageous will print out the below (as if `bc` was a line on its own and yanked using `Y`):
```
bc
abc
def
```
There are similar issues for the lowercase `p` as well. If all lines in a selection ends with newlines I think that NeoVintageous treats them as if they were yanked with `Y` or `yy` and that is the reason why copy/pasting using Visual mode is different when compared to VIM. The regression my patch introduced was because it did the opposite and pasted all text as if it were copied through Visual mode.

A way I can think of to resolve this to expand on the Resgisters class in vi/registers.py so that instead of storing plain strings it stores an object that can hold state (such as the manner in which it was copied) ... does that make sense or am I off mark?

**Comment by gerardroche** [comment]
It makes sense. You probably know that part of the code better than I do right now.

Also keep in mind linewise visual selections. A simple, albeit not useful examples,`Vyp`, `VyP`
