### ISSUE TITLE
Release on Package Control

### ISSUE THREAD

**Issue by gerardroche** [NeoVintageous/NeoVintageous#252]
What do you think about making a release and publishing on Package Control, v1.0.0? cc @trishume

I've been trying to do a massive refactor of the codebase, renaming everything from "vintageous" to "neovintageous` but it breaks too many things. I think it's better to make a release now as v1.0.0 and instead of trying to do a big refactor all at once I'll make small incremental refactorings along with fixes instead.

The current master works fine for me, I've had no problems at all. I'm Linux, what system have you tested on?

Also, what do you think about adding a hook before install to disable Vintageous, Vintage, or Six if the user has them installed? I think they could cause some really weird issues if we don't disable them.

Here's the suggested package control channel submission: https://github.com/gerardroche/package_control_channel/commit/0d9cf54c2a6c64e7d8f46c46cfa58aca79312aaf. Should we increase the build version requirement?

**Comment by trishume** [comment]
Sounds good to me. I don't think a massive refactor renaming everything is necessary other than renaming the Python package and imports, it's all internal other than the settings and command names. And I don't think we should rename the settings and command names so that it is a drop in replacement and people's configs continue to work.

Suggested package control channel looks good. I did a bunch of testing of the latest version on OSX and it seems to work well, I'm testing on the latest dev build of ST3.

I agree we should look for a nice way to tell the user to disable Vintageous or Vintage if they have them installed. And perhaps to disable either Six or NeoVintageous depending on which they want since in that case it is unclear.

**Comment by SCdF** [comment]
The README now implies it's done, but the link goes here: https://packagecontrol.io/browse/authors/NeoVintageous and AFAICT there is no actual package on there yet.

**Comment by gerardroche** [comment]
@SCdF Thanks. I've added notes about it in the readme. It's in the Package Control channel PR queue: https://github.com/wbond/package_control_channel/pull/6292.
