### ISSUE TITLE
Block cursor

### ISSUE THREAD

**Issue by borela** [NeoVintageous/NeoVintageous#261]
Currently neovintageous uses the current line highlight to simulate a block cursor, a better alternative is an implementation like: 

* https://github.com/karlhorky/BlockCursorEverywhere 

That would allow better control of the cursor by having a specific scope that people could use in the color schemes like `neovintageous-block-cursor`, `neovintageous-line-selection`, etc... basically you could add different colors to the cursors and selections.

**Comment by gerardroche** [comment]
A block cursor would be great. The block cursor in vim is good. Generally it inverts the foreground and background so the block colour changes depending on the context. That's really the solution.

BlockCursorEverywhere is good idea but I've played around with it and it has a few issues:

Regions have curved corners which doesn't lend well to making a block cursor. They also have outlines which are impossible style.

![one](https://cloud.githubusercontent.com/assets/44148/26765374/bc32e7b6-4972-11e7-85ba-5237bd61d7ed.png)

I've updated the block cursor plugin to work specifically in NeoVintageous: https://github.com/gerardroche/BlockCursorEverywhere/tree/3325342e1e5c6649359fea8d06325cc38c1449a2
 
I've removed the outline from region, but because it still has curved corners it itsn't that good.

![two](https://cloud.githubusercontent.com/assets/44148/26765383/fdb65236-4972-11e7-98a4-42a3f86f3e7a.png)

Also, notice the invisibles are displayed in the cursor block (the grey dot).

Compare that to the default behaviour of sublime in NeoVintageous with a colour scheme like Monokai in the [molokai](https://github.com/gerardroche/sublime-molokai) package:

![3](https://cloud.githubusercontent.com/assets/44148/26765399/4fb2a652-4973-11e7-9ffc-48054f3736fa.png)

There are still lots of issues with that, but through testing BlockCursorEverywhere still doesn't solve the problem well enough. 

A proper block cursor would be great though.

**Comment by borela** [comment]
I am using a modified version without the outline too and I agree, the rounded corners look bad. Is there a way to color the block generated by neovintageous that is different from the selection color?

**Comment by gerardroche** [comment]
> Is there a way to color the block generated by neovintageous that is different from the selection color? 

No, I don't think there is.

> The only real issue with the current approach is that I am not sure how to color the foreground when in normal mode.

I don't think you can: `selectionForeground` doesn't work, even if it did the selection foreground might not be the same colour you want as the cursor. I think as you tinker with it more and more you find more and more issues you didn't notice before.

The BlockCursorEverywhere plugin first commit was over 5 years ago. I think anybody that has tried to solve this quickly realises that the only real way to solve this in the core of sublime with a proper solution like vim block cursor.

**Comment by nimafazeli** [comment]
After installing the new version of ST yesterday, the cursor in normal mode takes the same background as the color scheme and does not invert the color anymore. It is almost invisible and hard to tell where the cursor is.
This seems to be particularly severe when `highlight_line` is enabled in dark color schemes where the background is gray.
I played around with my settings for the cursor a bit but no change. I wonder whether new version of ST causes the issue. Any hint?
Thanks
