### ISSUE TITLE
Sort Lines command sorts whole file

### ISSUE THREAD

**Issue by xtian** [NeoVintageous/NeoVintageous#273]
When I use the **Sort Lines** command from the command palette with several lines selected, every line in the file is sorted instead of just the ones selected. This happens when using both visual mode and mouse selection, but if I use mouse selection the sort will be correctly scoped the second time I invoke the command.

If I add NeoVintageous to my `ignored_packages` config, then Sort Lines works as expected.

Sorry I don't have any more information! I haven't had time to investigate further.

**Comment by borela** [comment]
What's strange is that if you use the shortcut `F9`, it works correctly, only when you try to access the command palette that the selection from the visual mode seam to lose effect.

**Comment by gerardroche** [comment]
Thanks. F9 works. I think the issue is something to do with a focus change when invoking ctrl+p. You might prefer a custom mapping, for example using your .vintageousrc file:

Open the file if from the Command Palette: `ctrl+shift+p` select `NeoVintageous: Open My .vintageousrc File`

```
:let mapleader=,
:vmap <leader>s <F9>
```

See https://github.com/NeoVintageous/NeoVintageous#the-vintageousrc-file

**Comment by xtian** [comment]
Just a note: this affects other line permutation commands (such as `Permute Lines: Reverse`) as well

**Comment by gerardroche** [comment]
@xtian Thanks! The fix should resolve all issues running any command from the Command Palette.

**Comment by JonathanHolvey** [comment]
@gerardroche I'm still seeing this issue. When selecting in visual mode and using <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd> to sort the selection, the entire file is sorted instead.

Was this fixed in the PR mentioned above? I'm using NeoVintageous version 1.12.0 in Sublime Text build 3207.

**Comment by gerardroche** [comment]
@JonathanHolvey This should have been fixed since 1.6.0. There was also a improved fix for issues like this in v1.14.1. Try the latest version and see if that resolves it. If not, can you try post some deug information via https://github.com/NeoVintageous/NeoVintageous/blob/master/ISSUE_TEMPLATE.md#additional-information

**Comment by JonathanHolvey** [comment]
Yes! @gerardroche Package Control updated NeoVintageous to version 1.14.2 today. After restarting Sublime Text the issue is resolved. Thanks.
