### ISSUE TITLE
Suggestions about plugins

### ISSUE THREAD

**Issue by webtotma** [NeoVintageous/NeoVintageous#276]
Is it possible to implement analogs of the plugins is[ vim-xkbswitch](https://github.com/lyokha/vim-xkbswitch) and  [vim-easymotion](https://github.com/easymotion/vim-easymotion)?
There are plugins acejump and easymotion for sublime text, but their functionality differs from the original.

**Comment by gerardroche** [comment]
I'm looking into vim-easymotion, maybe 1.4 or 1.5. 

vim-xkbswitch is probably a little too big in scope and the sublime core api capabilities is probably be a blocker.

**Comment by karamfil** [comment]
Easy motion would be super amazing!

And you guys are awesome too!!

**Comment by karamfil** [comment]
Hey @gerardroche,

Just curious why are you looking at 1.4 or 1.5 and not the latest version?

**Comment by gerardroche** [comment]
The current version is 1.3 and we're using a [semver](http://semver.org/)-ish versioning. Adding a new plugin is a big enough feature addition to bump the minor version.

**Comment by karamfil** [comment]
Oh you were talking about NeoVintageous ^_^; My bad

Well, is there any documentation what need to be done to port a plugin from vim to here?

**Comment by gerardroche** [comment]
I'm afraid there's no documentation for writing plugins. The current plugin api is a bit of a mess. The only way to learn is to look at the existing plugins in `lib/extras` (the folder is not called plugins because of an issue in the ST core), but it's not really a public api and I'm refactoring and changing things so the api could change at any time. 

If you're looking to extend or customise things, the next version I'm working on adds the ability to map to ex commands and ST commands in your `.vintageousrc` file. This is easiest to understand with some examples that my own `.vintageousrc` currently contains (this is only a recent feature addition not yet pushed):

>  Mapping to basic ex commands is supported in the form `:excommand<CR>`.
>
>  To map to a Sublime Text command, the command must start an uppercase letter, to avoid confusion with builtin ex commands e.g. `:YourCommand<CR>`. The command is converted to snake case.

```
" Multiple cursors
nnoremap <C-n> gh
snoremap <C-n> j
snoremap <C-p> k
snoremap <C-x> l
snoremap i <Esc>i

" Search & Replace
nnoremap <leader>h :ShowFindInFilesPanel<CR>
nnoremap <leader>f :ShowFindResults<CR>

" Folds
nnoremap zc :Fold<CR>
nnoremap zo :Unfold<CR>
nnoremap zM :FoldAll<CR>
nnoremap zR :UnfoldAll<CR>

" Test plugin
" https://github.com/gerardroche/sublime-test
" https://github.com/gerardroche/sublime-phpunit
nnoremap <leader>t :TestNearest<CR>
nnoremap <leader>T :TestFile<CR>
nnoremap <leader>a :TestSuite<CR>
nnoremap <leader>l :TestLast<CR>
nnoremap <leader>g :TestVisit<CR>
```

Some of the commands mapped to in the above map to custom commands like the `nnoremap <leader>f :ShowFindResults<CR>` which is command that display a Find Results view if it's open. This is useful when you do a search a replace and want to go jump back to the Find Results view.

```
from sublime_plugin import WindowCommand

class ShowFindResultsCommand(WindowCommand):
    def run(self):
        for view in self.window.views():
            if view.name() == 'Find Results':
                # Clear any visual selection.
                sel = view.sel()[0].begin()
                view.sel().clear()
                view.sel().add(sel)

                return self.window.focus_view(view)
```

**Comment by gerardroche** [comment]
With the latest 1.4.0 release you map to Sublime Text commands, which means you can map to commands provided by plugins like AceJump (emacs style version of EasyMotion).

Example mappings for AceJump:

```
let mapleader=,

" AceJump plugin
" https://github.com/ice9js/ace-jump-sublime
nnoremap <leader><leader>a :AceJumpAfter<CR>
nnoremap <leader><leader>c :AceJumpChar<CR>
nnoremap <leader><leader>d :AceJumpAddCursor<CR>
nnoremap <leader><leader>i :AceJumpWithinLine<CR>
nnoremap <leader><leader>l :AceJumpLine<CR>
nnoremap <leader><leader>s :AceJumpSelect<CR>
nnoremap <leader><leader>w :AceJumpWord<CR>
```

See the forum post on latest release: [NeoVintageous 1.4.0 released zap KAPOW](https://forum.sublimetext.com/t/neovintageous-1-4-0-released-zap-kapow/33172).

**Comment by gerardroche** [comment]
Closing this but I've added this to the list of suggestions for future plugin implementations here: https://github.com/NeoVintageous/NeoVintageous/issues/855

**Comment by gerardroche** [comment]
Closing this but I've added this to the list of suggestions for future plugin implementations here: https://github.com/NeoVintageous/NeoVintageous/issues/855
