### ISSUE TITLE
Ctrl key no longer work after update

### ISSUE THREAD

**Issue by TrCaM** [NeoVintageous/NeoVintageous#293]
I turned on the ctrl key option but after the update it no longer override the defaut ctrl key of the system ( may be or it doesn't work at all). Now I have to revert back to previous version to use ctrl key.

**Comment by gerardroche** [comment]
How have you enabled the ctrl keys?

`Menu > Preferences > Settings`:

```
    {
        "vintageous_use_ctrl_keys": true
    }
```

Try restarting Sublime Text. And if you can enabled debug logging to see what's happening because I'm unable to reproduce:

The Sublime Text startup log can be found in the console: `Menu > View > Show Console`.

Command and input logging can be enabled from the console: `sublime.log_commands(True); sublime.log_input(True)` (run the commands in input box at the bottom of the console panel via `Menu > View > Show Console`).

Also please let me known what OS and version ST you're on.

**Comment by TrCaM** [comment]
I'm on Windows 10 and ST 3.

Here is the screenshot that shows the option to use ctrl keys is enable but Neo Vintageous couldn't overwrite those command.

[https://imgur.com/wQIKiAP](url)

**Comment by gerardroche** [comment]
The keys are not being set to Neovintageous. You should be seeing something like:

```
chr evt: j (0x6a)
command: press_key {"key": "j"}
chr evt: j (0x6a)
command: press_key {"key": "j"}
chr evt: k (0x6b)
command: press_key {"key": "k"}
key evt: control+c
command: press_key {"key": "<C-c>"}
key evt: control+]
command: press_key {"key": "<C-]>"}
key evt: control+y
command: press_key {"key": "<C-y>"}
```

Do you have a keymaps file in your User directory? `Menu > Browse Packages...` go to the User directory and see if you have any keymaps in there that overriding NeoVintageous.

You can also check your keymaps via `Menu > Preferences > Key Bindings`. 

I'm going to check on Windows system myself in hour or so to make sure it's not a OS issue.

**Comment by mbert** [comment]
I had the same problem. It was caused by the following code in my settings: 

    {
	"vintageous_use_ctrl_keys": "true"
    }

Removed the quotes around `true`, and things were fine again.

**Comment by gerardroche** [comment]
I think in the next major version we'll enable the ctrl keys by default, because that's how vim works by default.
