### ISSUE TITLE
:w not saving

### ISSUE THREAD

**Issue by qazip** [NeoVintageous/NeoVintageous#315]
:w is not saving my files. Any idea why?
```
>>> sublime.log_commands(True)
>>> :w
  File "<string>", line 1
    :w
    ^
SyntaxError: invalid syntax
```

**Comment by qazip** [comment]
I re-installed and it's now working.

**Comment by gerardroche** [comment]
The reason you got that error is because you were trying to execute a cmdline line mode commands from the Sublime Text console, which is not the same as the command line mode. 

To show the ST console `Menu > View > Show Console`. Typing `:w` inside this console will cause the error you describe.

To show the cmdline mode press `:`.
