### ISSUE TITLE
Loss of ST clipboard copy and paste functionality in insert mode

### ISSUE THREAD

**Issue by nimafazeli** [NeoVintageous/NeoVintageous#364]
Hi and thanks for the great work

I seem to have an issue with clipboards and registers (which are a bit confusing for people who are not used to it imho).

### Description
* In both cases whether I *enable* or *disable*  `vintageous_use_sys_clipboard` I get the following behavior:
1- When I am in insert mode and select a piece of text, `ctrl-x` does not cut the text. Instead takes me to normal mode. 
2- In insert mode `ctrl-c` does not copy the text, it does not take me to normal mode right away but as soon as I use an arrow key it takes me to normal mode.

### Expected behaviour
I expect to have the functionalities of sublime text when in insert mode. 
Please let me know if this is not a correct expectation.

### Versions
I am using windows 10 and ST version 3.1.1

**Comment by gerardroche** [comment]
You can disable ctrl keys via the `vintageous_use_ctrl_keys` settings.

See `:h nv` or [here](https://github.com/NeoVintageous/NeoVintageous/blob/a0c0237045ba186b26326d4818c06b11450b3fb1/res/doc/neovintageous.txt).

If you want to use ctrl keys you can override those keymaps in you keymaps file: `Menu > Preferences > Key Bindings`.

For example to make Neo always copy with ctrl+c add:

```
    // Copy in NeoVintageous in any mode.
    { "keys": ["ctrl+c"], "command": "copy" },
```

**Comment by nimafazeli** [comment]
Thanks for the prompt reply. It resolved my previous issue.

On a relevant matter, I added 
` noremap <leader>p :PasteFromHistory<CR>`
to my rc file and now I can use the nice built-in function `paste_from_history` that suits me much better than using vim registers.

Is there a way that I can add what I copy or cut in normal mode to that history stack?
I tried this 
```
noremap y: Copy
noremap x: Cut
```
but whatever I do in normal mode does not seem to be added to the history stack. Seems that sublime is unaware of content of the clipboard in normal mode although I have activated `vintageous_use_sys_clipboard`

**Comment by gerardroche** [comment]
I'm not sure what you mean by history stack, maybe this:

```
" Yank and paste using system clipboard.
" http://www.drbunsen.org/the-text-triumvirate/
noremap <leader>y "+y
noremap <leader>Y "+Y
noremap <leader>p "+p
noremap <leader>P "+P
noremap <leader>yy "+Y
```

**Comment by gerardroche** [comment]
The `vintageous_use_sys_clipboard` setting controls if copying via yank, delete, change, etc. commands should put the content in the system clipboard. 

When it's off yanking a line `Y` will not put the content in the clipboard, instead you can explicitly put it in the clipboard via `"+Y` i.e. the `+` register. I map the register variants to my leader key:

```
noremap <leader>y "+y
noremap <leader>Y "+Y
noremap <leader>p "+p
noremap <leader>P "+P
```

When `vintageous_use_sys_clipboard` is on then content via yank, delete, change, etc. commands are always put in the clipboard. But for some reason, and I don't know why yet, the content is never available via the paste_from_history command.

You can map to the builtin copy and cut commands:

```
noremap y :Copy<CR>
noremap x :Cut<CR>
```

The above commands will correctly put the copied or cut content into the clipboard and will be available via `paste_from_history`.

```
noremap <leader>h :PasteFromHistory<CR>
```

One issue is that the cut command doesn't work so well, because in VISUAL mode, after the cut it stays in VISUAL, but should really enter NORMAL mode. You could solve this by creating a user command that wraps the cut command and enters normal mode after the command, for example:

```
import sublime_plugin

class CustomCutCommand(sublime_plugin.TextCommand):

    def run(self, edit):
        self.view.run_command('cut')
        self.view.run_command('_enter_normal_mode')
``` 

This may break, when the `_enter_normal_mode` command renamed or removed.

**Comment by nimafazeli** [comment]
Thanks! this is great. 
I am not a programmer but plug-ins like yours are teaching me a great deal. Great job and I really appreciate the effort you are putting in here.

By the way, I have another suggestion:
**Allow pasting directly from the dropdown list given by `:reg` .**  
The drop-down list of `:reg` looks great and much better than clunky `paste_from_history` menu.
Here how it can go:
- Copy or cut a bunch of things without caring about the order they are sent to registers, 
- Run `:reg` to see the content of different registers 
- Select the register to be pasted, 
- Press `return` to paste it at the point.

This will mimic the `kill-ring` in emacs which I find extremely efficient because it is visual and does not require remembering the name of the register and typing down e.g. `"3P` to paste it. I find this very distracting to be honest and although I am sure vim ninjas must have had reasons to keep this functionality alive, I believe using the visual capabilities of ST can make the experience much better.

**Comment by gerardroche** [comment]
This is fixed in the next version. The clipboard history is now updated on operations such as yank, delete, change, when `vintageous_use_sys_clipboard` is enabled`, which means 

```
noremap <leader>h :PasteFromHistory<CR>
``` 

will work.
