### ISSUE TITLE
Disable Input Method when exiting Insert Mode

### ISSUE THREAD

**Issue by haolly** [NeoVintageous/NeoVintageous#374]
Something like this done in VscodeVim https://github.com/VSCodeVim/Vim#input-method 
This is a useful feature for CJK users, would you mind consider implement this in future ?

**Comment by gerardroche** [comment]
I'm not that familiar with input methods. Let me see if I understand the feature correctly. Using Chinese (Intelligent Pinyin) you enter insert via `Shift+a`, then to get to normal mode you need to hit `Esc` twice, but it should go to normal mode after one `Esc`. So from here: 

![keys](https://user-images.githubusercontent.com/44148/54661295-8581b000-4ad1-11e9-8c0c-59b990c11fc9.png)

It should only take one `Esc` to go to normal mode?

**Comment by haolly** [comment]
When you are using Chinese Pinyin input method, nether `a` or `shift+a` will make you going insert mode from normal mode.
When you are using Chinese Pinyin in insert mode, `ESC` will make you go to normal mode

**Comment by gerardroche** [comment]
`Shift+A` enters insert mode for me. `Esc` closes the input method dialog box, then another `Esc` enters normal mode. 

One issue I've found is that Sublime Text doesn't receive key events when the input method dialog is visible, which kind of makes sense, because it's a system utility. 

What OS are you using?

**Comment by haolly** [comment]
@gerardroche  windows 10

**Comment by gerardroche** [comment]
@haolly #547 may have fixed the issue? I haven't had a chance to test on Windows. I can't reproduce it on Linux.

**Comment by haolly** [comment]
@gerardroche  so, how can I test it ?

**Comment by gerardroche** [comment]
Just make sure you have at least version NeoVintageous 1.14.1 and see if it works as you expect. 

I think that I'm probably not understanding what the issue is.

> When you are using Chinese Pinyin in insert mode, ESC will make you go to normal mode

So when the Input Method is visible in insert mode like this:

![in](https://user-images.githubusercontent.com/44148/58071051-31f41700-7b93-11e9-8ac1-5453581879e5.png)

1. Pressing `<Esc>` should hide the Input Method. 
2. Then pressing `<Esc>` again should enter Normal mode.

Is this how it works for you? 

Or are you expecting it to do something else?  If you can show me steps to reproduce the issue and what is actually happening and what is expected to happen it will help.

**Comment by haolly** [comment]
1. Assume you are in insert mode, and use chinese input method
2, type `nihao` will not insert any charactor into the file, insteam the input method show some candidate for  you to choose.
2, When you at step 2, press space bar, the first candidate `你好`  will be inserted into file
3, Then you press ESC, it WILL turn to normal mode, BUT, when you press `i` or `h` and etc,  it will not go to insert mode, instead, the input method captured the input charactor, and show some candidate for you to choose

**Comment by gerardroche** [comment]
After step 2 pressing ESC enters normal mode, but pressing **any** key still displays the Input Method. 

So actually, all keys, for example h, j, l, k, w, b, etc. **all** of these cause the Input Method to be displayed. 

But what you want is that the Input Method to only be enabled when in insert mode, so that you use commands like h, j, l, k, w, b, etc. in normal mode?

Whereas, on my system, to disable the Input Method I have to press SHIFT, which is configurable:

![Screenshot from 2019-05-21 10-40-22](https://user-images.githubusercontent.com/44148/58085805-5660eb00-7bb5-11e9-8f2a-fdf9a56b79ed.png)

I'm not sure how to fix this, or even if it's possible yet. Have you any thoughts? What key do you press on your system to disable the Input Method?

**Comment by gerardroche** [comment]
It looks like we need to hook into the **enter Insert mode** and **enter Normal mode** to allow a user configurable script to run that toggles the Input Method. The script may be different from system to system hence the `vim.autoSwitchInputMethod.switchIMCmd` in the vscodevim plugin.

An example IM switcher for Vintage: https://packagecontrol.io/packages/IMSwitchForVintage.

**Comment by haolly** [comment]
Yes, something like IMSwitchForVintage

**Comment by gerardroche** [comment]
Re also  vim-xkbswitch #276

**Comment by gerardroche** [comment]
I will have a beta version of a input method plugin in the upcoming version 1.33.0. It will allow you to switch the input method on entering and exiting insert mode. It will need some testing from you guys because I don't use a feature like this so I'm not entirely familiar with usage.
