### ISSUE TITLE
Movement by visual line gj and gk is laggy

### ISSUE THREAD

**Issue by nimafazeli** [NeoVintageous/NeoVintageous#381]
I have mapped my motion keys to move by visual line instead of logical lines i.e:

```
noremap j  gj
noremap k gk
```

However, movement started to get very slow and jumpy as the file size grew. The file size is around 1500 lines and is  mostly prose.
Console log is filled with lines like following : 

```
2018-09-14 19:43:44,930 - INFO - key evt: g repeat_count=None do_eval=False check_user_mappings=False
2018-09-14 19:43:44,930 - DEBUG - sequence >>>g<<<
2018-09-14 19:43:44,945 - DEBUG - partial sequence >>>g<<<
2018-09-14 19:43:44,945 - DEBUG - resolved None -> g -> <ViOpenNameSpace (<unset>)>
2018-09-14 19:43:44,945 - INFO - opening namespace
2018-09-14 19:43:44,945 - DEBUG - key evt took 0.0156s
2018-09-14 19:43:44,945 - INFO - key evt: j repeat_count=None do_eval=False check_user_mappings=False
2018-09-14 19:43:44,945 - DEBUG - sequence >>>gj<<<
2018-09-14 19:43:44,945 - DEBUG - partial sequence >>>gj<<<
2018-09-14 19:43:44,945 - DEBUG - resolved None -> gj -> <ViMoveByScreenLineDown (<unset>)>
2018-09-14 19:43:44,945 - DEBUG - key evt took 0.0000s
2018-09-14 19:43:44,945 - INFO - view.run_command() {'is_jump': True, 'motion_args': {'count': 1, 'mode': 'mode_normal'}, 'motion': '_vi_gj'}
2018-09-14 19:43:44,945 - DEBUG - sequence >>><<<
2018-09-14 19:43:44,961 - DEBUG - partial sequence >>><<<
2018-09-14 19:43:44,961 - DEBUG - sequence >>><<<
2018-09-14 19:43:44,961 - DEBUG - partial sequence >>><<<
2018-09-14 19:43:44,961 - DEBUG - key evt took 0.0312s
```

Please let me know whether you need me to send more information.
Thanks in advance for any hint.

_Originally posted by @nimafazeli in https://github.com/NeoVintageous/NeoVintageous/issues/83#issuecomment-421434356_

**Comment by gustavobittencourt** [comment]
I'm having the same problem here with this remap.

It took me 5.21 seconds to jump through 258 lines of a LaTeX file without this remap (a clean `.vintageousrc` file); and 9.84 seconds with this.

Thank you guys!

My computer is:
MacBook Pro (15-inch, 2017)
2,9 GHz Intel Core i7
16 GB 2133 MHz LPDDR3
Intel HD Graphics 630 1536 MB

**Comment by gerardroche** [comment]
On my system (Linux) when pressing one key I get approx 0.0369s, if hold down the key I an average of about 0.0137s.

Without remapping I get 0.0195s, and ~0.0096s when I hold down the key.

Remapping j and k to gj and gk will naturally slow things down, the same happens in Vim.

There are some LaTeX tools plugins that can be cause of exacerbating performance issues, but it's a trade-off.

The performance issues were much worse, but there's certainly room for improvement.

FYI when mapping j and k to gj and gk, you can map gj and gk to j and k (this doesn't speed things up, just a tip):

```
nnoremap j gj
nnoremap k gk
nnoremap gj j
nnoremap gk k
```

Some debug information:

```
chr evt: j (0x6a)
command: _nv_feed_key {"key": "j"}
NeoVintageous: INFO    [cmds.py:263] key evt: j repeat_count=None do_eval=True check_user_mappings=True
NeoVintageous: DEBUG   [state.py:253] sequence >>>j<<<
NeoVintageous: DEBUG   [state.py:266] partial sequence >>>j<<<
NeoVintageous: DEBUG   [mappings.py:203] resolved None (sequence) -> j -> <NeoVintageous.nv.mappings.Mapping object at 0x7fd8334be2d0>
NeoVintageous: DEBUG   [cmds.py:346] command <NeoVintageous.nv.mappings.Mapping object at 0x7fd8334be2d0> (<class 'NeoVintageous.nv.mappings.Mapping'>, <class 'object'>)
NeoVintageous: DEBUG   [cmds.py:357] found user mapping...
NeoVintageous: DEBUG   [cmds.py:360] evaluating user mapping (mode=mode_normal)...
NeoVintageous: DEBUG   [state.py:253] sequence >>><<<
NeoVintageous: DEBUG   [state.py:266] partial sequence >>><<<
NeoVintageous: INFO    [cmds.py:373] user mapping j -> gj
NeoVintageous: DEBUG   [cmds.py:473] process notation keys gj for initial mode mode_normal
NeoVintageous: INFO    [cmds.py:263] key evt: g repeat_count=None do_eval=False check_user_mappings=False
NeoVintageous: DEBUG   [state.py:253] sequence >>>g<<<
NeoVintageous: DEBUG   [state.py:266] partial sequence >>>g<<<
NeoVintageous: DEBUG   [mappings.py:203] resolved None (sequence) -> g -> <ViOpenNameSpace (<unset>)>
NeoVintageous: DEBUG   [cmds.py:346] command <ViOpenNameSpace (<unset>)> (<class 'NeoVintageous.nv.vi.cmd_defs.ViOpenNameSpace'>, <class 'NeoVintageous.nv.vi.cmd_base.ViMotionDef'>, <class 'NeoVintageous.nv.vi.cmd_base.ViCommandDefBase'>, <class 'object'>)
NeoVintageous: INFO    [cmds.py:387] opening namespace
NeoVintageous: DEBUG   [cmds.py:279] key evt took 0.0018s (key=g repeat_count=None do_eval=False check_user_mappings=False)
NeoVintageous: INFO    [cmds.py:263] key evt: j repeat_count=None do_eval=False check_user_mappings=False
NeoVintageous: DEBUG   [state.py:253] sequence >>>gj<<<
NeoVintageous: DEBUG   [state.py:266] partial sequence >>>gj<<<
NeoVintageous: DEBUG   [mappings.py:203] resolved None (sequence) -> gj -> <ViMoveByScreenLineDown (<unset>)>
NeoVintageous: DEBUG   [cmds.py:346] command <ViMoveByScreenLineDown (<unset>)> (<class 'NeoVintageous.nv.vi.cmd_defs.ViMoveByScreenLineDown'>, <class 'NeoVintageous.nv.vi.cmd_base.ViMotionDef'>, <class 'NeoVintageous.nv.vi.cmd_base.ViCommandDefBase'>, <class 'object'>)
NeoVintageous: DEBUG   [cmds.py:279] key evt took 0.0020s (key=j repeat_count=None do_eval=False check_user_mappings=False)
NeoVintageous: INFO    [vim.py:107] command: _vi_gj {'mode': 'mode_normal', 'count': 1}
NeoVintageous: DEBUG   [state.py:253] sequence >>><<<
NeoVintageous: DEBUG   [state.py:266] partial sequence >>><<<
NeoVintageous: DEBUG   [state.py:253] sequence >>><<<
NeoVintageous: DEBUG   [state.py:266] partial sequence >>><<<
NeoVintageous: DEBUG   [cmds.py:279] key evt took 0.0137s (key=j repeat_count=None do_eval=True check_user_mappings=True)
```

**Comment by gerardroche** [comment]
I've been testing the performance of these commands trying to find the bottleneck. I've discovered a few interesting things.

**gj** and **gk** will naturally be slower than their **j** and **k** counterparts, because the **g** variants have to go through more lines, screen lines. For example consider:

```
Hello world! Hello world! Hello world! Hello world! Hello world! Hello world! Hello world! Hello world! Hello world! Hello world! Hello world! Hello world! Hello world! Hello world! Hello world! Hello world! Hello world! Hello world! Hello world! Hello world! Hello world! Hello world! Hello world! Hello world! Hello world! Hello world! Hello world! Hello world! Hello world! Hello world! Hello world! Hello world!
```

When wrapped at 80 characters it's **six** lines:

```
Hello world! Hello world! Hello world! Hello world! Hello world! Hello world!
Hello world! Hello world! Hello world! Hello world! Hello world! Hello world!
Hello world! Hello world! Hello world! Hello world! Hello world! Hello world!
Hello world! Hello world! Hello world! Hello world! Hello world! Hello world!
Hello world! Hello world! Hello world! Hello world! Hello world! Hello world!
Hello world! Hello world!
```

**gj** will take **six** times longer to go through those lines.

## How I tested

I tested against 300 of those lines, which is **1800** lines when wrapped.

```
Hello world! Hello world! Hello world! Hello world! Hello world! Hello world! Hello world! Hello world! Hello world! Hello world! Hello world! Hello world! Hello world! Hello world! Hello world! Hello world! Hello world! Hello world! Hello world! Hello world! Hello world! Hello world! Hello world! Hello world! Hello world! Hello world! Hello world! Hello world! Hello world! Hello world! Hello world! Hello world!
```

I also tested against 1800 hard-coded lines (the 300 lines with line breaks at 80 chars):

```
Hello world! Hello world! Hello world! Hello world! Hello world! Hello world!
Hello world! Hello world! Hello world! Hello world! Hello world! Hello world!
Hello world! Hello world! Hello world! Hello world! Hello world! Hello world!
Hello world! Hello world! Hello world! Hello world! Hello world! Hello world!
Hello world! Hello world! Hello world! Hello world! Hello world! Hello world!
Hello world! Hello world!
```

I tested **gj** and **gk** by mapping them to **j** and **k**:

```
noremap j  gj
noremap k gk
```

## Keyboard repeat and delay rates

The first bottleneck I discovered was not Sublime Text or NeoVintageous, it was my keyboard repeat and delay rates. I tweaked those (on Ubuntu):

```
$ gsettings set org.gnome.desktop.peripherals.keyboard repeat-interval 15
$ gsettings set org.gnome.desktop.peripherals.keyboard delay 180
```
![Screenshot from 2019-04-09 22-26-31](https://user-images.githubusercontent.com/44148/55836475-7f05b780-5b16-11e9-8efc-f7e415f859de.png)

## Timings

command | time | lines
--- | --- | ---
**j** | ~5s | 300 lines (not-wrapped)
**gj** | ~30s | 300 lines (wrapped ~1800 lines)
**j** | ~30s | 1800 hard-coded lines

I was surprised that **gj** was just as fast as **j** when tested against 1800 lines. It turns out that **gj** isn't slower than **j** (it's a little slower, but the difference is negligible).

At this point I wanted to see if plain old Sublime Text down-arrow was faster, so I disabled NeoVintageous and tested how long it takes the built-in Sublime Text down-arrow command  to go through 1800 lines.

command | time | lines
--- | --- | ---
**down-arrow** | ~30s | 1800 hard-coded lines

Hmm. The bottle is still the keyboard repeat and delay rates. The **j** and **gj** commands are no slower than using the built-in down-arrow key.

## Keyboard repeat and delay rates

The tests above uses a repeat-interval of 15 and a delay of 180:

```
$ gsettings set org.gnome.desktop.peripherals.keyboard repeat-interval 15
$ gsettings set org.gnome.desktop.peripherals.keyboard delay 180
```

This is as low as I could tweak these settings without having all kinds of issues. Issue that don't really have anything to do with NeoVintageous. It seems that the bottleneck is not NeoVintageous.  

For example, when you reduce the repeat-interval, you start to have issues using the built-in down-arrow: when the repeat is too fast, the cursor starts to jump erratically down the screen or it will not move at all until you stop pressing it, and then it catches up and jumps down the screen.

## Conclusion 

The built-in commands like down-arrow will always be slightly faster than NeoVintageous commands like **j** and **gj**. There are definitely some performance improvements that can be made to NeoVintageous, but they're not going to be major, because it looks like the bottlenecks are elsewhere.

If you're like me, then you might not have realised that **gj** is actually going through more lines that **j**, so naturally it's going to take a longer. It appears to take much longer, but it's actually doing what it's supposed to do: go screen-line by screen-line oppose to line by line.

There have been some optimisations in the core over the last few minor releases and there will be more coming in the next few minor releases.
