### ISSUE TITLE
Alt tab exits insert mode

### ISSUE THREAD

**Issue by guilhermeleobas** [NeoVintageous/NeoVintageous#385]
### Description

Whenever I am in `insert mode` editing a file and do a Ctrl Tab, NeoVintageous change the current mode to normal mode. Is this the expected behavior?

### Steps to Reproduce

Just Alt-tab/Cmd-tab while in insert mode.

### Expected behaviour

I was expecting ST to continues on insert mode rather than go back to normal mode. 

### Actual behaviour

ST changes to normal mode.

### Versions

Version 3.1.1 Build 3176
OS: Mac OS

**Comment by gerardroche** [comment]
No this is not expected behavior. Perhaps you have a keymap override. Check your keymaps: **Menu > Preferences > Key Bindings**. 

Also, are you using a .neovintagousrc file?

I may need some debugging information to help debug it: https://github.com/NeoVintageous/NeoVintageous/blob/master/CONTRIBUTING.md#debugging

**Comment by guilhermeleobas** [comment]
Hi @gerardroche,

Here is the content of my **Key Bindings** file:

```json
[
  { "keys": ["ctrl+tab"], "command": "next_view" },
  { "keys": ["ctrl+shift+tab"], "command": "prev_view" }
]
```

> Also, are you using a .neovintagousrc file?

Nope.

Below is the debugging info you asked for. See if that helps.
```
Package Control: Skipping automatic upgrade, last run at 2018-11-13 11:32:10, next run at 2018-11-13 12:32:10 or after
>>> sublime.log_input(True)
key evt: super+v
>>> sublime.log_commands(True)
command: drag_select {"event": {"button": 1, "x": 341.5859375, "y": 394.56640625}}
chr evt: i (0x69)
command: _nv_feed_key {"key": "i"}
command: drag_select {"event": {"button": 1, "x": 10.24609375, "y": 553.7421875}}
command: drag_select {"event": {"button": 1, "x": 9.171875, "y": 532.796875}}
command: drag_select {"event": {"button": 1, "x": 645.7421875, "y": 670.37109375}}
```

If it helps, I did a small screencast showing the bug:
https://imgur.com/a/47u0ePJ

**Comment by gerardroche** [comment]
You have a `ctrl+tab`  bound to new_view, which will revert to normal mode. There's no easy workaround that I can think of to get the behavior you want.

The only thing I can think of is to create a plugin that *decorates* the **next_view** command and handles the mode.

A basic example:

```
import sublime_plugin

class NeovintageousNextViewCommand(sublime_plugin.WindowCommand):

    def run(self):
        view = self.window.active_view()
        mode = view.settings().get('command_mode') if view else None

        self.window.run_command('next_view')

        if not mode:
            self.window.run_command('_enter_insert_mode')
```

Then use the keymaps `{ "keys": ["ctrl+tab"], "command": "neovintageous_next_view" },`

**Comment by guilhermeleobas** [comment]
Sorry @gerardroche, I was referring to Cmd+tab (or alt+tab) and not Ctrl-tab.

**Comment by gerardroche** [comment]
In you debug output:

```
Package Control: Skipping automatic upgrade, last run at 2018-11-13 11:32:10, next run at 2018-11-13 12:32:10 or after
>>> sublime.log_input(True)
key evt: super+v
>>> sublime.log_commands(True)
command: drag_select {"event": {"button": 1, "x": 341.5859375, "y": 394.56640625}}
chr evt: i (0x69)
command: _nv_feed_key {"key": "i"}
command: drag_select {"event": {"button": 1, "x": 10.24609375, "y": 553.7421875}}
command: drag_select {"event": {"button": 1, "x": 9.171875, "y": 532.796875}}
command: drag_select {"event": {"button": 1, "x": 645.7421875, "y": 670.37109375}}
```

Can press the keys causing the issue and post the output of the debug log?

**Comment by guilhermeleobas** [comment]
No debugging information is produced when I press Cmd+Tab. You can confirm this by looking at the [video](https://imgur.com/a/47u0ePJ).

Do you know if there is a way to start ST without plugins? Something like `vim -u NONE`. Or maybe initialize Sublime Text with just Neovintageous enable.

**Comment by gerardroche** [comment]
Ah yes, the focus is switching to the OS, e.g. app launcher, and when the focus switches, the mode resets to normal mode. 

There's no easy to fix this, it's partly a limitation in Sublime Text events. Sublime Text doesn't have an event for leaving to the focus of the enter and an event for returning. And it's partly due to the way in which modes are implemented in NeoVintageous.

This issue is mostly explained in https://github.com/NeoVintageous/NeoVintageous/commit/239b3bf69b52728cb2177b3ec6297ed3168fb346

> ...
> In Vim, the cursor is generally not reset to normal mode. When you enter
insert mode and move to another view, you stay in insert mode. When you
enter visual mode & move to another view the visual mode is cleared and
changes to normal mode and then the cursor moves to the other view and
stays in normal mode. Making NeoVintageous work like this will require
significant resign of how the mode state is handled.

Relates also to issues: #357 and #277

**Comment by shuhaowu** [comment]
Should this issue be closed? It's still a bug, right?

**Comment by zencephalon** [comment]
Yeah, I find this behavior a problem for my workflow still.

**Comment by shuhaowu** [comment]
Is there any known work around for this, or maybe does another plugin not do this?

**Comment by gerardroche** [comment]
@shuhaowu @zencephalon You can set your default mode to "insert", I don't know if that helps? See: https://github.com/NeoVintageous/NeoVintageous/blob/master/res/doc/neovintageous.txt#L722

If I'm understanding the issue correctly: when you are in insert mode and switch focus to another application the mode resets to normal mode. Setting your default mode to Insert mode may help but it may also have unwanted side-effects e.g. whenever you switch views it enter insert mode.

**Comment by shuhaowu** [comment]
This isn't quite right either as it deviates the behavior from vim. Also, wouldn't that work around mean if I leave sublime in normal mode switch to a different application and then come back, I'll get insert mode? That would be somewhat disorienting, as well...

**Comment by gerardroche** [comment]
Yes, that workaround would mean you get insert mode when you switch views or windows. That's obviously not a good workaround for you. Some people seem to like that. 

The main issue is due to the way the core mode handler works and limitations in ST: when you switch applications ST loses focus, then when you switch back to ST it receives focus and NeoVintageous "resets" the mode to normal mode (or insert mode if you set it as default). Am I understanding this correctly?

> In Vim, the cursor is generally not reset to normal mode. When you enter
insert mode and move to another view, you stay in insert mode. When you
enter visual mode and move to another view, the visual mode **is cleared** and
changes to normal mode, **then** the cursor moves to the other view and
stays in normal mode. Making NeoVintageous work like this will require
significant resign of how the mode state is handled.
> See https://github.com/NeoVintageous/NeoVintageous/commit/239b3bf69b52728cb2177b3ec6297ed3168fb346

You're correct that the way Neo doesn't handle the mode the same as Vim, it's a known issue. It will require some major redesigning in the core, a lot of progress has been made, but it's a big change.

**Comment by shuhaowu** [comment]
Do you have anymore details on how you would like to rework the mode handling? With that info, maybe the community can pick this task up (including myself).

**Comment by intelfx** [comment]
> You're correct that Neo doesn't handle the mode the same as Vim, it's a known issue.

Maybe this issue should be reopened?

**Comment by evaera** [comment]
`"vintageous_reset_mode_when_switching_tabs": false`
