### ISSUE TITLE
How to map function keys?

### ISSUE THREAD

**Issue by eduardoarandah** [NeoVintageous/NeoVintageous#564]
### Description

Can't map function keys

### Steps to Reproduce

First mapping works, second doesn't

```
nnoremap <leader>s :ToggleSideBar<CR> 
nnoremap <F6> :ToggleSideBar<CR> 
```

**Comment by gerardroche** [comment]
Hmm, it worked for me? Did you reload the rcfile (use the command palette or restart Sublime)?

Maybe F6 is shodowed by an OS key binding? Run this in your console: `sublime.log_input(True)` to get some input logging to see if Sublime is receiving the key event. **Menu > View > Show Console**

**Comment by gerardroche** [comment]
Also I recommend using the neovintageous specific toggle command:

```
nnoremap <leader>s :Neovintageous action=toggle_side_bar<cr>
```

It's slightly different from the builtin toggle sidebar commands in that it puts focus on the sidebar. You can use **j** and **k** in the sidebar.

You can then configure a map to toggle the side bar when it has focus:

> Note that to enable the toggle the side bar when the side bar has focus you
need to configure a special key binding. Goto  Menu > Preferences > Key
Bindings and add the following: >

```
    [
        {
            "keys": [",", "d"],
            "command": "neovintageous",
            "args": { "action": "toggle_side_bar" },
            "context": [ { "key": "control", "operand": "sidebar_tree" } ]
        }
    ]
```


The reason is so that you can press `,s` to open the sidebar and put focus on it to use **j** and **k** to navigate it, and then press `,s` to close it, which puts focus back on the view.

**Comment by eduardoarandah** [comment]
Oh! you're right!

I found out the command shadowing my mapping with this:

```
sublime.log_commands(True); 
sublime.log_input(True); 
sublime.log_commands(True); 
sublime.log_result_regex(True);
```
Thanks

**Comment by sourcevault** [comment]
Hi,

I am facing a similar issue with remapping `f12` to `Esc`.

`.neovintageousrc`

```
noremap h <left>
noremap j <down>
noremap k <up>
noremap l <right>

nnoremap <F14> <Esc>

nnoremap <F12> <Esc>
```

sublime console output :

```
key evt: f12
command: goto_definition
key evt: f12
command: goto_definition
key evt: f12
command: goto_definition
key evt: f12
command: goto_definition
key evt: down
key evt: down
key evt: f14
key evt: f14
key evt: f14
```

I was expecting something like this to show up :

```
command: nv_feed_key {"key": "<esc>"}
command: nv_enter_normal_mode {"mode": "mode_insert"}
```

*Note:* I have `F14` on my keyboard enabled via autohotkey.
