### ISSUE TITLE
Issue with Emmet's increase or decrease numbers commands

### ISSUE THREAD

**Issue by duranivan** [NeoVintageous/NeoVintageous#571]
First of all, thanks for continuing the development of the original Vintageous. This package is one of the reasons I still love Sublime Text over other editors such as VSCode...

### Description

OK, so, While in normal mode When using Emmet's `Increment/Decrement number` commands, visual model gets automatically activated, so if I want to move the cursor away (e.g. with `j` or `k` ), then I have to use `Esc` to get out of visual mode, otherwise other text will be highlighted.

I know it is not a big issue but when working a lot with numbers, for example in CSS, having to escape from visual mode every time I use the Emmet's commands to change numbers, it gets a bit annoying.

This doesn't happen in VSCode Vim's package.

### Steps to Reproduce

While in normal mode, use one of the Emmet's commands to increase or decrease a number, then automatically visual mode is activated.

### Expected behaviour

When one of the Emmet's commands to increase or decrease numbers is used, Neovintageous should remain in normal mode

### Versions

`startup, version: 3208 osx x64 channel: dev`

**Comment by gerardroche** [comment]
This is pretty much an Emmet issue because Emmet creates the visual selection regardless of whether NeoVintageous is installed or not.

A workaround would be to create a NeoVintageous mapping that wraps the Emmet commands and automatically invokes `<Esc>` after the command is run e.g.:

```
nnoremap <C-up> :RunEmmetAction action=increment_number_by_1<CR><Esc>
```

This wouldn't be good for everyone because it requires the ctrl keys to be enabled. But even if you have ctrl keys enabled this currently won't work because mappings currently don't support trailing commands.

A workaround would be to create some user commands like:

```
class RunEmmetActionIncrementNumberByOne(sublime_plugin.TextCommand):
    def run(self, edit):
        self.view.run_command('run_emmet_action', {'action': 'increment_number_by_1'})
        self.view.run_command('_enter_normal_mode')
```

Then create mappings: 

```
nnoremap <C-up> :RunEmmetActionIncrementNumberByOne<CR>
```

Or use a leader key if you don't like ctrl keys enabled (we're currently trying to figure out how best to implement granular control of keys like the ctrl keys #470):

```
nnoremap <leader><up> :RunEmmetActionIncrementNumberByOne<CR>
```

None of these solutions are particularly ideal, because it's essentially an Emmet issue. Perhaps ask the Emmet developers to implement an option to disable the visual selection after operations like increment/decrement?

**Comment by duranivan** [comment]
Thanks for your answer. I understand it is not possible at the moment or it is an issue on Emmet's side.

**Comment by duranivan** [comment]
`nnoremap <C-up> :RunEmmetAction action=increment_number_by_1<CR><Esc>` works now

Thanks!
