### ISSUE TITLE
Mapping ALT keys

### ISSUE THREAD

**Issue by taylorthurlow** [NeoVintageous/NeoVintageous#579]
### Description
I'd like to be able to bind ALT keys in my `.neovintageousrc`.

### Steps to Reproduce
Add this to your `.neovintageousrc`

~~~vimscript
nnoremap <A-j> :m .+1<CR>==
~~~

### Expected behaviour
I am able to use the `Alt+j` key binding to move a single line down a line in normal mode.

### Actual behaviour
The console logs an error (`ValueError: 'A-j' is not a known key`) and I am unable to use the binding.

### Versions
`1.16.0`

----

Let me know if this is out of scope due to being able to bind ALT keys using the normal sublime bindings.

**Comment by gerardroche** [comment]
Mapping `<A-...>` is supposed to be the same as mapping `<M-...>` so that needs to be fixed by aliasing `<A-...>` to `<M-...>`. 

Mapping alt keys is currently not supported, but it will be easy to add support. The only issue would be that the default alt keybindings will no longer work because NeoVintageous would be overriding them. This is one of the reasons we have settings for enabling/disabling ctrl keys and super keys:

```

                                                  *'vintageous_use_ctrl_keys'*
'vintageous_use_ctrl_keys'
                        boolean (default: false)
        Enable key bindings prefaced by the ctrl-key.

                                                 *'vintageous_use_super_keys'*
'vintageous_use_super_keys'
                        boolean (default off)
        Enable key bindings prefaced by the super-key, otherwise known as the
        command-key in OSX, and as the windows-key in Windows.
```

I can easily support alt keys with a new setting to enable them: `vintageous_use_alt_keys`, which I think we'll disable by default until maybe version 2.0. We're trying to figure out how best to enable granular control of the keys, see https://github.com/NeoVintageous/NeoVintageous/issues/470.

**Comment by gerardroche** [comment]
I think it will be a good idea to support the `winaltkeys' option too. This means that by default the alt menu keys would continue to work. 

For example currently when you press `alt+f` it opens the file menu. With the default setting of "menu" that will still work. 

Supporting this option means we can probably enable the alt keys by default or probably don't even need the `vintageous_use_alt_keys` setting, because with the option set to **menu** Sublime should just work as normal i.e. only the unbound alt keys would be mappable by default. 

```
'winaltkeys' 'wak'	string	(default "menu")
			global
			{not in Vi}
			{only used in Win32, Motif, GTK and Photon GUI}
	Some GUI versions allow the access to menu entries by using the ALT
	key in combination with a character that appears underlined in the
	menu.  This conflicts with the use of the ALT key for mappings and
	entering special characters.  This option tells what to do:
	  no	Don't use ALT keys for menus.  ALT key combinations can be
		mapped, but there is no automatic handling.  This can then be
		done with the |:simalt| command.
	  yes	ALT key handling is done by the windowing system.  ALT key
		combinations cannot be mapped.
	  menu	Using ALT in combination with a character that is a menu
		shortcut key, will be handled by the windowing system.  Other
		keys can be mapped.
	If the menu is disabled by excluding 'm' from 'guioptions', the ALT
	key is never used for the menu.
	This option is not used for <F10>; on Win32 and with GTK <F10> will
	select the menu, unless it has been mapped.
```

**Comment by gerardroche** [comment]
In the version you can enable alt keys via the setting `vintageous_winaltkeys`.

It accepts three values: true, false, or "menu".

* If true (default) the alt keys are not registered by neovintageous
* If false, all alt keys are registered by neovintageous
* If "menu", then alt keys are registered by neovintageous if the menu is not visible or or none of the menu's are bound to that alt key, for example `alt+f` will still invoke the menu instead of neovintageous overriding it.  

There are a few alt keys that still need to be implemented, there's a list of known missing keys in the roadmap: https://github.com/NeoVintageous/NeoVintageous/issues/404
