### ISSUE TITLE
goto matching bracket '%'  inherits strange behavior from vim

### ISSUE THREAD

**Issue by dindon-sournois** [NeoVintageous/NeoVintageous#613]
### Description

NeoVintageous inherits a curious feature from vim as typing '%' on a bracket can match commented code. I'm sure people will find uses for it and it replicates vim behaviour so it may not be a bug after all. However I think it would be better to use Sublime's "move to bracket" feature which seems to work correctly.

Is there a way to make NeoVintageous behave like I want ?

### Steps to Reproduce

Consider the following C code :

```
void f() {
  { // 1
  // {
  } // 2
} // 3
```

### Expected behaviour

Pressing '%' on the bracket tagged as 1 should move the cursor to the bracket tagged as 2

### Actual behaviour

Pressing '%' on the bracket tagged as 1 move the cursor to the bracket tagged as 3, and other matches are incorrect.

### Versions

startup, version: 3207 windows x64 channel: stable

**Comment by gerardroche** [comment]
Vim actually ignores commented brackets for some syntaxes, for example try php:

`test.php` (where `|` is the cursor), pressing `%` skips the commented bracket:

```
function x() {
    // {
|}
```

But if you try that code in a txt file pressing `%` will jump to the commented bracket, which makes sense because a text file doesn't have a comment syntax.

The same is true for the code you posted in a c file e.g. `test.c`:

```
void f() {
  { // 1
  // {
  } // 2
} // 3
```

So, yes this is something I want to fix. Also relates to https://github.com/NeoVintageous/NeoVintageous/issues/243

**Comment by dindon-sournois** [comment]
It is worth noting it also concerns non-commented code like strings. See the following C code for an example :
```
void f() {
 char s = '{';
}
```
For now I've mapped '%' to Sublime Text's "move_to to=brackets" and I am not aware of any undesirable side effect : `nnoremap % :MoveTo to=brackets<CR>`

**Comment by gerardroche** [comment]
The sublime MoveTo brackets is a bit quirky. I've fixed it so that things like comments and strings are ignored. Will be available in the next minor release. Hopefully soon.
