### ISSUE TITLE
Support for chaining ex commands with '|' (vertical bar)

### ISSUE THREAD

**Issue by dindon-sournois** [NeoVintageous/NeoVintageous#615]
### Description

I'm trying to map vim bindings to a chain of ex commands.

### Steps to Reproduce

Pressing the following keys :

`:w | :q`
then press `<CR>`

### Expected behaviour

Save and close file.

### Actual behaviour

Some log in Sublime console :

```
Traceback (most recent call last):
File "C:\Users\pathto\Sublime Text Build 3207 x64\Data\Installed Packages\NeoVintageous.sublime-package\nv/commands.py", line 881, in on_done
File "C:\Users\pathto\Sublime Text Build 3207 x64\Data\Installed Packages\NeoVintageous.sublime-package\nv/ex_cmds.py", line 1662, in do_ex_cmdline
File "C:\Users\pathto\Sublime Text Build 3207 x64\Data\Installed Packages\NeoVintageous.sublime-package\nv/ex_cmds.py", line 114, in inner
File "C:\Users\pathto\Sublime Text Build 3207 x64\Data\Installed Packages\NeoVintageous.sublime-package\nv/ex_cmds.py", line 1369, in ex_write
File "C:\Users\pathto\Sublime Text Build 3207 x64\Data\Installed Packages\NeoVintageous.sublime-package\nv/ex_cmds.py", line 1342, in _do_write
File "C:\Users\pathto\Sublime Text Build 3207 x64\Data\Installed Packages\NeoVintageous.sublime-package\nv/ex_cmds.py", line 1273, in _check_is_readonly
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: '| :q'
```

### Versions

startup, version: 3207 windows x64 channel: stable

**Comment by gerardroche** [comment]
Chaining commands in ex mode is currently not supported.

**Comment by dindon-sournois** [comment]
Thank you for your answer. I was trying to work around this issue by using recursive mapping but it doesn't seem to be supported either. It is weird because I can find some [reference ](https://github.com/NeoVintageous/NeoVintageous/commit/613e77c2aef2dbb17ec224c46326f9c19acbcbef)about nmap for example. Any idea ?

I'm doing this to test :
`:nmap z z` 
and getting the message 
> Not an editor command: nmap z z

**Comment by gerardroche** [comment]
The recursive mapping were removed and replaced with the non recursive commands https://github.com/NeoVintageous/NeoVintageous/blob/master/CHANGELOG.md#removed-3.

The recursive mappings were removed because they were not implemented as recursive mappings, and removing them now in preference of the non-recursive may prevent some potential problems in the future if the recursive mapping commands are ever implemented.

Recursive mappings can cause infinite loops, in Vim too, not just Sublime. They're not that easy to implement and there have been other priorities so it unlikely they'll implemented any time soon.

With `:w | :q` you can use `:wq` instead.

What are you trying solve with a recursive mapping and maybe I can give you some alternatives?

**Comment by dindon-sournois** [comment]
Thank you for your explanation. As you may have guess I was using `:w | :q` as an example.
I was trying to create one binding that save the current unsaved changes on my `.neovintageousrc` file and reload it with a chain of :
```
:Neovintageous action=open_rc_file<CR>
:w<CR>
:Neovintageous action=reload_rc_file<CR>
```

**Comment by gerardroche** [comment]
Support for chaining with `<Bar>` has been added in the next version:

The special `<Bar>` character can be used to separate commands from the next command.

Example

```
nnoremap <leader>m :SlurpFindString<Bar>:SlurpReplaceString<Bar>:ShowPanel panel=find_in_files<CR>
```

You can also chain ex commands or mix ex and user commands:

```
noremap <C-s> :w<Bar>:SomeOtherCommand<CR>
```
