### ISSUE TITLE
Can't move cursor left and right in visual line mode

### ISSUE THREAD

**Issue by schffp** [NeoVintageous/NeoVintageous#640]
### Steps to Reproduce
Enter visual line mode, try pressing "h" or "l"

### Expected behaviour
In regular neovim the cursor can be moved horizontally (h, l) in visual line mode. This functionality is sometimes needed, in order to select a block via jumping to the closing bracket.

### Actual behaviour
After entering visual line mode (V) the cursor cant be moved horizontally.

### Versions
startup, version: 3211 windows x64 channel: stable

**Comment by gerardroche** [comment]
This isn't possible in Sublime Text, it has not way of moving the cursor within a selection.

To move the active cursor from end to the other press `o`. 

Commands like `%` should still work too, for example where `|` is the cursor press `V%` will visually select to the closing brace and pressing `%` again will move the visual selection back to the opening brace.

```
<?php
|if (true) {
    // ...
} 
```

I've just noticed that this won't work in some situations for example pressing `V%` works properly by moving the selection to he closing paren, but then pressing `%` doesn't work because the closing paren is not the last character in the line. There's no good way to solve this in Sublime Text because there's no way to move the cursor within the selection.

```
|    return sprintf(
        "%s %s%s\n",
        $date,
        $type,
        $description
    );
```

**Comment by schffp** [comment]
That's unfortunate to hear.. It's impossible to properly select html tags then, for example.
Would you consider submitting a feature request?
https://forum.sublimetext.com/c/ideas-and-feature-requests

**Comment by gerardroche** [comment]
I opened a feature request here: https://github.com/SublimeTextIssues/Core/issues/3033

**Comment by gerardroche** [comment]
Closing as this is now a known Sublime Text issue and there's nothing to do until Sublime Text adds the necessary features.

**Comment by gerardroche** [comment]
Closing and moving the issue to the [known issues](https://github.com/NeoVintageous/NeoVintageous/issues/404) section of the roadmap.
