### ISSUE TITLE
jk to leave insert mode

### ISSUE THREAD

**Issue by pianocomposer321** [NeoVintageous/NeoVintageous#648]
According to the :help neovintageous page, imap and inoremap are not supported yet. Is there a workaround, like by using sublimes own keybindings? if not, when are these commands planned to be supported?

**Comment by pianocomposer321** [comment]
Never mind, I figured it out. For those of you who have the same question, add a keymapping to the command _nv_feed_key, with the arguments being the keys (in the format that vim uses) that you want it to map to.

**Comment by pianocomposer321** [comment]
for example:
{ "keys": ["j", "k"], "command": "_nv_feed_key", "args": {"key": "<esc>"} }

**Comment by gerardroche** [comment]
The mapping you posted above will cause unexpected conflicts, instead use the following:

```
    {
        "keys": ["j", "k"],
        "command": "_enter_normal_mode",
        "args": {"mode": "mode_insert"},
        "context": [{"key": "vi_insert_mode_aware"}]
    },
```

The important thing above that it is only bound to insert mode. This is important so that it doesn't conflict with other modes.

See https://github.com/NeoVintageous/NeoVintageous/blob/master/res/doc/neovintageous.txt#L500

There's no timeline on when insert mode mappings might be implemented. Nonetheless I think maybe we could make the workaround a little less verbose.

**Comment by pianocomposer321** [comment]
Thank you. I stumbled across this keybinding in the help file shortly after posting here. Shows what help reading the docs really can be (sometimes). :)

Thanks.

btw, I found that looking into some of the python source code can help with other commands that you may need to map to. Maybe this should be mentioned in the docs?

**Comment by justinlaughlin** [comment]
> The mapping you posted above will cause unexpected conflicts, instead use the following:
> 
> ```
>     {
>         "keys": ["j", "k"],
>         "command": "_enter_normal_mode",
>         "args": {"mode": "mode_insert"},
>         "context": [{"key": "vi_insert_mode_aware"}]
>     },
> ```

I just wanted to add that in the current version of NeoVintageous the code to put in your settings is the following (change "_enter_normal_mode" to "nv_enter_normal_mode"). My muscle memory is already used to "kj" as my escape so I needed the custom bind rather than the convenient new options "vintageous_i_escape_jj" and "vintageous_i_escape_jk".

```
 {
     "keys": ["j", "k"],
     "command": "nv_enter_normal_mode",
     "args": {"mode": "mode_insert"},
     "context": [{"key": "vi_insert_mode_aware"}]
 },
```
