### ISSUE TITLE
Abolish plugin not working

### ISSUE THREAD

**Issue by domibarton** [NeoVintageous/NeoVintageous#692]
**Describe the bug**  

First of all, THANK YOU for this amazing SublimeText package! I've never seen such a good Vim integration in any other editor before. KUDOS!

Now to the bug:

The Abolish plugin is not working in my Sublime Text. I'm not sure if this is a bug or just a user error ;) Everything else apart from that plugin works.

**To Reproduce**  

- Install NeoVintageous
- Activate it
- Create a new document and with the following content:

```
facility
facilities
address
addresses
```

- Now Try to use the Abolish plugin by using commands such as:

```
:iabbrev  seperate  separate
:%Subvert/facilit{y,ies}/building{,s}/g
:Subvert/address{,es}/reference{,s}/g
```

**Expected behavior**  

The commands should work and you should have the document altered like this:

```
building
buildings
reference
references
```

If you type `seperate` it should be replaced with `separate`.

**Actual behavior**  

The document isn't altered and the commands are not accepted.
Result of the commands:

`:iabbrev  seperate  separate` results in:
![image](https://user-images.githubusercontent.com/4124099/74838010-01f4c280-5323-11ea-9472-20f32196fc53.png)

`:%Subvert/facilit{y,ies}/building{,s}/g` results in:
![image](https://user-images.githubusercontent.com/4124099/74838047-1c2ea080-5323-11ea-82a1-67cf94f9323c.png)

`:Subvert/address{,es}/reference{,s}/g` results in:
![image](https://user-images.githubusercontent.com/4124099/74838066-2b155300-5323-11ea-8e95-3e1a53d851f5.png)

**Versions**  
Sublime Text version: `startup, version: 3211 osx x64 channel: stable`

**Additional Information**  

What I did so far:

- Read the NeoVintageous documentation
- Had a look at your issues
- Read `:help neovintageous`
- Read `:help abolish`

I found the following snippet in the abolish docs:

```
This plugin is only available if 'compatible' is not set.
```

What is `compatible`? Where can I find it?  Is that a Vim option? How do I get available Vim options, because `:set` doesn't work in ST3.

I hope it's not just a "user error" caused by "not reading the docs properly" :)

**Comment by gerardroche** [comment]
Only the case mutations algorithms are currently supported e.g. `cru` to make the current word uppercase. There's a todo in the roadmap (https://github.com/NeoVintageous/NeoVintageous/issues/404) to implement the additional features. 

The `compatible` option isn't relevant in NeoVintageous because backwards compatibility with older versions of Vim is mostly ignored.

The `:set` command should work. Not all Vim options are implemented.

```
==============================================================================

OPTIONS                                                           *nv-options*

Some vim options are supported in your rc file. For example, to always start
with the 'ignorecase' option on, add the following line your rc file: >

    set ignorecase

To always start with it off: >

    set noignorecase

List of available options:

    'autoindent', 'belloff', 'hlsearch', 'ignorecase', 'incsearch', 'list',
    'magic', 'menu', 'minimap', 'modeline', 'modelines', 'number', 'sidebar',
    'spell', 'statusbar', 'winaltkeys', 'wrap', 'wrapscan'

Examples: >

    set noignorecase
    set nomenu
    set nominimap
    set nomodeline
    set sidebar
    set statusbar
    set winaltkeys=menu

Try `:help 'option name'` for help on individual options.
```

There are some additional options in the upcoming 1.19.0 version:

* Added [#685](https://github.com/NeoVintageous/NeoVintageous/issues/685): `'shell'` option e.g. `:set shell=/bin/bash` (used for `:!{cmd}` commands)
* Added [#678](https://github.com/NeoVintageous/NeoVintageous/issues/678): `'textwidth'` option e.g. `:set textwidth`, `:set notextwidth`
* Added [#677](https://github.com/NeoVintageous/NeoVintageous/issues/677): `'tabstop'` option e.g. `:set tabstop`, `:set notabstop`
* Added [#679](https://github.com/NeoVintageous/NeoVintageous/issues/679): `'expandtabs'` option e.g. `:set expandtabs`, `:set noexpandtabs`

And two changes:

* Changed [#404](https://github.com/NeoVintageous/NeoVintageous/issues/404): `'winaltkeys'` option is now "menu" by default
* Changed [#404](https://github.com/NeoVintageous/NeoVintageous/issues/404): `'ignorecase'` option is now false by default

See https://github.com/NeoVintageous/NeoVintageous/blob/master/CHANGELOG.md

**Comment by domibarton** [comment]
Thanks for the clarifications and the updates. That's awesome!
