### ISSUE TITLE
Support for CTRL+A/X (increment/decrement)

### ISSUE THREAD

**Issue by perchrc** [NeoVintageous/NeoVintageous#737]
VIM's CTRL+A/X for incrementing and decrementing the number under the cursor are often very useful, and I miss them a lot in Sublime. I found a few existing plugins which could potentially be ported.

**Comment by gerardroche** [comment]
You need to enable ctrl keys because they are disabled by default. You can use the Command Palette command **NeoVintageous: Toggle CTRL keys** to quickly toggle them on and off.

Also see the docs: `:help nv` or [res/doc/neovintageous.txt](https://github.com/NeoVintageous/NeoVintageous/blob/master/res/doc/neovintageous.txt). Also https://blog.gerardroche.com has lots of release information and tips.
