### ISSUE TITLE
change vim-sneak keybinding

### ISSUE THREAD

**Issue by bangedorrunt** [NeoVintageous/NeoVintageous#738]
hi,

is it possible to remap `s` or `S` keybinding to another key?. i'm using these keys very often and wanna keep them from being overriden.

**Comment by tsujp** [comment]
+1 I've had a look at the docs and cannot get it to work, for example using `f` or `F`. Anyone got some insight?

**Comment by gerardroche** [comment]
No it's currently not possible to specifically map sneak keys without over-riding some keys, but that's something that would be useful. 

Currently when you enable sneak it will override:

* `s` in Normal, Visual, and Visual Line modes
* `z` in Operator pending mode
* `S` in Normal mode
* `Z` in Visual, Visual Line, and Operator Pending modes

**Comment by gerardroche** [comment]
> By the way: cl is equivalent to s, and cc is equivalent to S.
> https://github.com/justinmk/vim-sneak#how-dare-you-remap-s

**Comment by gerardroche** [comment]
It's hard to implement this because it requires redesigning how plugins are
loaded. Currently the plugins are loaded at startup. We don't have access to
settings at startup. We could unload the mappings or overwrite them later, but
this requires design changes too.

What I can do in the meantime is offer environment variables to set the sneak
mappings. This will require a restart of Sublime and probably your OS to take
effect.

The way it would work is you would set environment variables. Example on Linux:

Add to `~/.profile`:

```
export NEOVINTAGEOUS_SNEAK_MAP_S=f
export NEOVINTAGEOUS_SNEAK_MAP_BIG_S=F
export NEOVINTAGEOUS_SNEAK_MAP_Z=z
export NEOVINTAGEOUS_SNEAK_MAP_BIG_Z=Z
```

Then restart your system.

I will implement this for the next version. I've already tested it and it seems
to work.  I hope this will help until a better solution can be implemented.

**Comment by sourcevault** [comment]
But the environmental variable solution wont work on windows ?

I want to test remapping sneak "s" to "e".

but I guess have to wait for it, it's nothing urgent.

**Comment by gerardroche** [comment]
@sourcevault you can set environment variables on Windows. It's Somewhere is system settings, look for Environment Variables. Here in the Vim docs it has instructions: https://github.com/NeoVintageous/NeoVintageous/blob/dec805b6cce9c80aefae6d7f60e18e31badbdf5c/res/doc/os_dos.txt#L56


You can set environment variables for each user separately through the
System Properties dialog box.  The steps to do that:
1. Type Windows Key + R to open the "Run" dialog box.
2. Enter "sysdm.cpl" and press the "OK" button.  The "System Properties"
   dialog box will open.
3. Select the "Advanced" tab and press the "Environment Variables..." button.
   The "Environment Variables" dialog box will open.
4. Select an existing variable in the "User variables" list and press the
   "Edit..." button to edit it.  Or press the "New..." button to add a new
   variable.
5. After you finished editing variables, press the "OK" button to save the
   changes.
