### ISSUE TITLE
Escaping from ST's own multicursor selection removes all selections

### ISSUE THREAD

**Issue by chenglou** [NeoVintageous/NeoVintageous#742]
**Describe the bug** 
With multiple regions selected using ST's built-in mechanism (`cmd-d` and `cmd-ctrl-g`) and `vintageous_multi_cursor_exit_from_visual_mode` defaulting to `false`, pressing on escape removes all selections instead of going back to normal mode.

Clarification: this bug only happens when the selections were started using `cmd-d` and `cmd-ctrl-g` instead of an ordinary visual selection (or nv's own `gh`) followed by `cmd-d` or `cmd-ctrl-g`.

**Versions**  
Not relevant.

**Additional Information**  
I'm using ST's built-in multiple selection mechanism in favor of nv's own, partially due to muscle memory, but more importantly due to `cmd-d` and `cmd-ctrl-g` (select all occurrences) behaving differently, and precisely the way I expected, regarding subword selections (e.g. starting with `cmd-d` only selects whole word matches. Starting with a selected region then using `cmd-d` selects subword matches).

**Comment by gerardroche** [comment]
At first I thought that would be expected behaviour because you're using ST's built-in multiple selection mechanism, but no it works for me. 

The first to do is enable some logging to see if Neo is receiving the `Esc` key, perhaps there's something overriding it:

Show the Sublime Text console log: **Menu > View > Show Console**. Command and input logging are enabled by running the following commands in input box at the bottom of the console: `sublime.log_commands(True) and sublime.log_input(True)`. See [CONTRIBUTING.md](https://github.com/NeoVintageous/NeoVintageous/blob/master/.github/CONTRIBUTING.md).

You'll get something like:

```
chr evt: i (0x69)
command: _nv_feed_key {"key": "i"}
key evt: shift+right
command: move {"by": "characters", "extend": true, "forward": true}
key evt: shift+right
command: move {"by": "characters", "extend": true, "forward": true}
key evt: shift+right
command: move {"by": "characters", "extend": true, "forward": true}
key evt: control+d
command: find_under_expand
key evt: control+d
command: find_under_expand
key evt: control+d
command: find_under_expand
key evt: escape
command: _nv_feed_key {"key": "<esc>"}
key evt: escape
command: _nv_feed_key {"key": "<esc>"}
```

I entered insert mode, selected 3 chars, made 3 multiple selections via `ctrl+d`, pressed escape (put me in normal mode for the multiple selections), and then escape again cleared the multiple selections.

Btw I use `ctrl-d` all the time too.

> Starting with a selected region then using cmd-d selects subword matches.

I think making a visual selection and then entering multiple cursor mode (`gh`) would be the same.

**Comment by chenglou** [comment]
Yeah to repro this bug you have to _not_ have anything pre-selected, and stay in normal mode. So the full repro is:
- have nothing selected, no extra nv config
- `cmd-d`, `cmd-d`
- `esc`
- see that both selections got removed

Here's the log:

```
command: drag_select {"event": {"button": 1, "x": 1799.5625, "y": 281.2734375}}
command: find_under_expand
command: find_under_expand
command: _nv_feed_key {"key": "<esc>"}
```

**Comment by gerardroche** [comment]
Ah yes, I have ctrl keys enabled. `ctrl+d` is scroll down when ctrl keys are enabled so I've never seen that issue. When ctrl keys are enabled you can also use `ctrl+n` to create multiple selections (same as `gh`). I usually use `ctrl+d` from insert mode.

I think I'll have a fix shortly.

**Comment by chenglou** [comment]
Thanks a lot!
