### ISSUE TITLE
Surround-any?

### ISSUE THREAD

**Issue by chenglou** [NeoVintageous/NeoVintageous#743]
I used to use Atom's [vim-mode-plus](https://github.com/t9md/atom-vim-mode-plus) and two big quality-of-life improvements I didn't think I was gonna miss were:
- An "any" surround so that I didn't have to specify which pair I'm surrounding
- Eliding the need for the "any" key above

So the result is that typing `cs'` changes the closest surrounding pair of whatever into `'`, and `ds` deletes the closest surrounding pair of whatever.

The realization is that 95% of the time the target surround is the closest pair, and that typing e.g. `cs"'` is a bit cumbersome. 

I'm not advocating changing the default; just wondering whether this can be done. I've been using both the atom and this sublime plugin extensively (need to switch around editors for work purposes) and this ended up being one of the bigger convenience changes.

**Comment by gerardroche** [comment]
This won't be possible because `cs'` would clash with commands like `cs'"`. You could possible have a timer such that if no replacement character is pressed (in the above command `"`) then it would use a heuristic to find a target, but this isn't straight forward in ST (related issue here https://github.com/NeoVintageous/NeoVintageous/issues/308).

We could possibly create a plugin that would give the option to adapt the existing cs, ds, etc. commands to do what you want but you lose the existing commands unless we implement the timer functionality. It's a lot of work that impacts the core and other commands.

Another alternative is implement these commands as a plugin and allow them to be bound to custom mappings via your neovintageousrc file e.g. to to your mapleader. This functionality is not implemented et either though (related issue https://github.com/NeoVintageous/NeoVintageous/issues/738).

I think the last solution is probably the best but it requires other core features and changes to be implemented first.

**Comment by gerardroche** [comment]
Closing this but I've added this to the list of suggestions for future plugin implementations here: https://github.com/NeoVintageous/NeoVintageous/issues/855
