### ISSUE TITLE
_nv_feed_key changed to nv_feed_key

### ISSUE THREAD

**Issue by jeffbdavenport** [NeoVintageous/NeoVintageous#751]
This is a notification to anyone who is trying to figure out why suddenly all of their custom NeoVintageous keybindings are no longer working.

This is because the `_nv_feed_key` was renamed to `nv_feed_key`

So if you have keybindings like this

```
{"keys": ["ctrl+j"], "command": "_nv_feed_key", "args": {"key": "<esc>"}}
```

Just delete the underscore before `nv_feed_key` and they will work again.

**Comment by malthejorgensen** [comment]
I believe the same goes for all other commands – e.g. `_enter_normal_mode` is now `enter_normal_mode`.

List of commands [before](https://github.com/NeoVintageous/NeoVintageous/blob/47b4afde6bce0399b621960ccaa3417a6593b40c/nv/commands.py#L243-L376) and [after](https://github.com/NeoVintageous/NeoVintageous/blob/7804f487d317126098cf33777fb55245ee8aef33/nv/commands.py#L243-L376).

**Comment by gerardroche** [comment]
All commands that started with a leading underscore have been renamed with a prefix "nv_" instead. This was to support ST4 and Python 3.8 because ST4 now ignores commands that start with an underscore, which is not bad thing. However, it was oversight not to at least document the changes when I made the release. 

> In ST4 Python 3.8 support all commands that start with underscore are ignored. This breaks NeoVintageous, so all commands need to be renamed.
>
> Prefix all commands with "nv_", some examples:
> 
> old | new
> --- | ---
> `_enter_normal_mode` | `nv_enter_normal_mode`
> `_enter_insert_mode` | `nv_enter_insert_mode`
> `_nv_feed_key` | `nv_feed_key`
> `_vi_w` | `nv_vi_w`
> `_vi_w` | `nv_vi_w`
> 
> https://github.com/NeoVintageous/NeoVintageous/issues/749

I'm wondering if it's worth while at this point to add a backwards compatible patch?
