### ISSUE TITLE
pasting with p or P  does not work when multiple cursors are enabled

### ISSUE THREAD

**Issue by sepisoad** [NeoVintageous/NeoVintageous#786]
**Describe the bug**  
pasting with p or P  does not work when multiple cursors is enabled

**To Reproduce**  
1. move cursor inside a word
2. type `gh` to enable multiple cursor
3. type a to select all occurrences of the word under curser 
4. type `p` to paste text from clipboard

**Expected behavior**  
It is expected to pasted the copied text from clipboard under each cursor

**Actual behavior**  
nothing happens

**Versions**  
Sublime Text: 4 (build 4113)

**Comment by gerardroche** [comment]
With the new additions pasting to multiple cursor selections is much more flexible.

There are some quirks to be mindful of but I think the way the paste contents are applied are the most obvious.

If all the items in paste register are the same (e.g. yanking a multiple cursor will create n items in the register):

- No matter how many selections there are the same content is pasted at all multi cursors. 

If the paste contents are different then (e.g. create some multiple cursors on different content and yank):

- if the number of paste items are **more** than the selections then the items are pasted up to the count of selections.
- if the number of paste items is **less** than the selections then it's a no-op because is there a reasonable way to guess at how the contents should be pasted?
