### ISSUE TITLE
Allow to map :w to lsp_save

### ISSUE THREAD

**Issue by frat3rius** [NeoVintageous/NeoVintageous#787]
It would be great if remapping `:w` to `lsp_save` would be possible. As described here:

https://github.com/sublimelsp/LSP/issues/1725

without it format on save isn't possible with LSP plugin. I've tried `noremap :w :LspSave<CR>` which does work, but `:` doesn't start vim command line anymore. Only sane solution at this time is:

`noremap <C-s> :LspSave<CR>`

Otherwise we have no way to use lsp_save other then command palette or other keybinding. 

If such remap is possible then sorry for creating an issue. I've searched through issues and help nv without any solution to this problem.

**Comment by gerardroche** [comment]
Yes, mapping `:w` will override `:`.

Implementing [`:autocmd`](http://vimdoc.sourceforge.net/htmldoc/autocmd.html) might help resolve this.

For example in Vim to run a function pre save:

```
:autocmd BufWritePre * call TrimWhiteSpace()
```

So implemented autocmd might allow something like:

```
:autocmd BufWritePre * :LspSave<CR>
```

**Comment by gerardroche** [comment]
With a new feature in the next release you can map multiple commands using `<Bar>` to separate commands :

```
noremap <C-s> :w<Bar>:LspSave<CR>
```

**Comment by mabugaj** [comment]
Yup LspSave does save the file. Problem is that I came from vim and I really like the ability to save with :w rather then <C-s>. Nevertheless glad to hear that.

**Comment by gerardroche** [comment]
I can add a setting to run an ex command post write, example

```
"vintageous_on_post_write_ex_cmd": ":LspSave<CR>"
```

This would run the lsp save command whenever you run any write command `:w`.

Because lsp is saving too this will result in the file being saved twice. I don't know if that's an issue for you. I'm surprised lsp doesn't have an setting to automatically run the lsp routine post file save.

**Comment by mabugaj** [comment]
@gerardroche it's hard for me to say if saving twice won't cause any further problems (I don't know the internal logic, some events or so...?). I think that this might be the problem in case of big files when some additional formatting take place.

Nevertheless if it's going to work properly than I think we can go this way.

Right now I'm back with vim (actually neovim) which unfortunately feels like home to me. If there's anything I can do (some research/testing) I'm willing to participate.

**Comment by gerardroche** [comment]
I would assume that the Vim lsp plugin executes its routine after the file write event e.g. `:autocmd BufWritePost * call TrimWhiteSpace()`. 

I think it would probably be better for the sublime lsp plugin to add similar functionality. For example the plugin could add an option to run its routine post save instead of doing the save.

**Comment by SBuercklin** [comment]
Is there any update on this? The commits above  for `vintageous_on_post_write_ex_cmd` aren't on `master`

**Comment by gerardroche** [comment]
I decided to add specific support for lsp saving. 

Enable `vintageous_lsp_save` to override `save` via `:w` to handle LSP Code-Actions-On-Save.

The reasons I chose a specific support instead of a post save hook is the post save hook might cause double saving and might not even work properly because the view would already be saved.
