### ISSUE TITLE
Searching with "/" not working properly in build 4121

### ISSUE THREAD

**Issue by dive-deeper** [NeoVintageous/NeoVintageous#793]
**Describe the bug**  
Normally, after searching with "/" we press enter to move to the selection and hide the search bar. Now, when we press enter a literal new line is inserted into the search bar.
I started noticing this behaviour in version 4121.

**To Reproduce**  
1. Press / to start a search
2. Type in something
3. Press enter

**Expected behavior**  
When we press enter the search bar disappears and we move to the location of the found string

**Actual behavior**  
A literal new line is entered into the search bar

**Versions**  
version: 4121 linux x64 channel: stable

**Comment by dive-deeper** [comment]
Apologies. I have tried recreating it in my secondary laptop without success.

On my primary computer I commented out my settings and disabled all packages but I still get this error. However, I have noticed it's not only with the search but also for any command e.g. :w or even with Sublime's "native" search. But it probably has more to do with something I messed up myself rather than with Neovintageous (funnily enough the problems started when I updated, so maybe some API change or sth).

If I find the source of the problem I'll write it in this thread, but it should be safe to close it for now.

BTW, this is the log_command output:
```
command: nv_vi_slash
command: git_gutter_blame {"is_event": true, "line": 0}
command: insert {"characters": "\n"}
command: left_delete
```
So it seems it literally takes the enter key as an "insert char \n".

**Comment by uncle-betty** [comment]
I'm facing the same issue. Maybe I can help troubleshoot this? I am on Linux and also on build 4121.

I generated the log below by searching for the word "mark".

  * After typing "/mark" all occurrences of the word "mark" are highlighted as expected.
  * When I then hit enter, a newline character seems to get appended to the search term. This makes the highlighting disappear and I get a "E486: Pattern not found: mark" message instead.
  * When I then hit backspace, the newline seems to get removed again and the highlighting reappears.

```
chr evt: / (0x2f)
command: nv_feed_key {"key": "/"}
NeoVintageous: INFO    [    commands.py: 515] key evt: / count=None eval=True mappings=True
NeoVintageous: DEBUG   [    commands.py: 540] mode: mode_normal
NeoVintageous: INFO    [    mappings.py: 192] resolved <ViSearchForward> mode=None sequence=None (<class 'NeoVintageous.nv.vi.cmd_defs.ViSearchForward'>, <class 'NeoVintageous.nv.vi.cmd_base.ViMotionDef'>, <class 'NeoVintageous.nv.vi.cmd_base.ViCommandDefBase'>, <class 'object'>)
NeoVintageous: INFO    [         vim.py: 124] command: nv_vi_slash None
command: nv_vi_slash
NeoVintageous: DEBUG   [       state.py: 243] evaluating...
NeoVintageous: DEBUG   [       state.py: 245] not runnable!
NeoVintageous: INFO    [    commands.py: 524] key processed in 0.0056 secs
chr evt: m (0x6d)
chr evt: a (0x61)
chr evt: r (0x72)
chr evt: k (0x6b)
key evt: enter
command: insert {"characters": "\n"}
```

**Comment by gerardroche** [comment]
Neo doesn't override the default ST enter key keymap in the the command line mode so that makes me think that you have a plugin installed that is overriding the enter key or you have a custom keymap overriding it.

For example the only way I can reproduce the issue is by editing my user key bindings file: 

*Command Palette > Preferences: Key Bindings*

```
    { "keys": ["enter"], "command": "insert", "args": {"characters": "\n"} },
```

In your log output something is triggering `command: insert {"characters": "\n"}` and I'm pretty sure it's not neovintageous because nv only defines two enter key mappings:

```
{"keys": ["enter"], "command": "show_panel", "args": {"panel": "output.Command-line", "toggle": true}, "context": [{"key": "setting.nv_cmdline_output"}]},
{"keys": ["enter"],     "command": "nv_feed_key", "args": {"key": "<cr>"},         "context": [{"key": "vi_command_mode_aware"}]},
```

## Debugging

Open your user keybindings and see if there is a rogue key binding overriding the enter key.

Try disabling NeoVintageous and testing the the input panel directly, for example:

Disable Neovintageous and then create an input panel by running the following code in the Console:

`Menu > View > Show Console`

```
sublime.active_window().show_input_panel('caption', 'initial text', None, None, None)
```

If the issue still persists with NeoVintageous disabled then there may be a rogue plugin overriding the enter key or possibly a ST bug. Try disabling some plugins to see if there another plugin is causing the issue.

**Comment by dive-deeper** [comment]
I have to admit I copied my User "Package" (sublime-text/Packages/User) which contains all of the installed packages and shortcuts, then deleted Sublime Text and reinstalled... And the problem wasn't there anymore.
If it didn't come from custom shortcuts or packages I cannot explain myself where it came from, maybe something went wrong during the update from ST3 to ST4

**Comment by uncle-betty** [comment]
Thank you very much for your quick response. I checked and, yes, there is a line... but it's in the default keymap:

```
tlo@nona:~$ grep -r \"enter\".*\"insert\" ~/.config/sublime-text-3
/home/tlo/.config/sublime-text-3/Packages/Default/Default (Linux).sublime-keymap:	{ "keys": ["enter"], "command": "insert", "args": {"characters": "\n"} },
tlo@nona:~$ 
```

Note that the directory under `~/.config` is still called `sublime-text-3`, even though I'm using ST4.

I removed anything ST-related under `~/.config` and `~/.cache` for a complete reset, reinstalled the packages - and things now work like a charm. Also, now there isn't any mapping:

```
tlo@nona:~$ grep -r \"enter\".*\"insert\" ~/.config/sublime-text
tlo@nona:~$ 
```

So, I guess something did indeed go wrong when I upgraded from ST3 to ST4 and it only started showing with build 4121, just as @dive-deeper suspects.

As far as I am concerned, this issue is solved. Hopefully, our learnings will come in handy for others who run into the same situation.

Thanks again, @gerardroche, for your quick response. It's much appreciated.
