### ISSUE TITLE
Port hop.nvim to neovintageous.

### ISSUE THREAD

**Issue by vinoff** [NeoVintageous/NeoVintageous#808]
I am aware that NV already supports sneak. However, I much prefer [hop.nvim](https://github.com/phaazon/hop.nvim). It requires much less interaction/keys to jump to a particular spot in the screen.

Would something like this be in scope of NV, or since there is already sneak, it is unlikely to happen?

**Comment by gerardroche** [comment]
I can't see this being implemented any time soon. But mostly due to a limitation in ST. For the same reason EasyMotion or AceJump has not been implemented (https://github.com/NeoVintageous/NeoVintageous/issues/276). There is currently no reasonable way to show the jump targets in ST. The phantoms feature in ST almost gets us there but there is no way to overlay the phantom on top of the view text to show the target.

**Comment by gerardroche** [comment]
Closing this but I've added this to the list of suggestions for future plugin implementations here:

https://github.com/NeoVintageous/NeoVintageous/issues/855
