### ISSUE TITLE
travel_to_pane commands can't be mapped

### ISSUE THREAD

**Issue by Amparose** [NeoVintageous/NeoVintageous#813]
**Describe the bug**  
travel_to_pane commands can't be mapped.

**To Reproduce**  
Add mappings to `.neovintageousrc`:

```vim
nnoremap <C-J> :TravelToPane direction=down
nnoremap <C-K> :TravelToPane direction=up
nnoremap <C-L> :TravelToPane direction=right
nnoremap <C-H> :TravelToPane direction=left
```

**Expected behavior**  
`⌃hjkl` should work like `⌘k ←↓↑→`.

**Actual behavior**  
They don't.

**Versions**  
- Sublime Text 4126
- NeoVintageous 1.26.1

**Comment by gerardroche** [comment]
Hmm, try changing the hjlk to lowercase in the mapping:

```
nnoremap <C-j> :TravelToPane direction=down
nnoremap <C-k> :TravelToPane direction=up
nnoremap <C-l> :TravelToPane direction=right
nnoremap <C-h> :TravelToPane direction=left
```

I think it should work with the uppercase too but I'm not sure that would be simple fix.

**Comment by Amparose** [comment]
Lowercase `hjkl` works.

Also, in case anyone this is desirable to others, I forgot to add `<CR>` to the end of each line.

**Comment by gerardroche** [comment]
I'm going to close this because ...

In Vim, the case of `{char}` in `<C-{char}>` does not matter; thus `<C-A>` and `<C-a>` are equivalent. But in Sublime the case of `{char}` is case-sensitive, using the `SHIFT` key will produce a different key event. The advantage is that you can have mappings for both `<C-A>` and `<C-a>` and not just one or the other.

In Sublime the lowercase ones are the same as Vim, and then you have the optional advantage of using the uppercase ones in mappings.
