### ISSUE TITLE
Get extremely slow when editing big files

### ISSUE THREAD

**Issue by hronro** [NeoVintageous/NeoVintageous#817]
When editing a big file (like a 20MB JavaScript file), Sublime Text with NeoVintageous becomes extremely slow.

There is no performance issue when using the built-in Vintage package.

**Comment by gerardroche** [comment]
Do you have some example files I can test against?

**Comment by gerardroche** [comment]
I can't reproduce the issue. Large files will naturally be slower for some things, but I don't see a general slow down for basic things. If you could try get some debug details from logging and plugin performance profile it might be helpful to diagnose where the issue is. https://github.com/NeoVintageous/NeoVintageous/blob/master/.github/CONTRIBUTING.md
