### ISSUE TITLE
<C-w> v & <C-w> s support

### ISSUE THREAD

**Issue by worldwalker2000** [NeoVintageous/NeoVintageous#818]
An integral part of my vim usage is opening two files side by side with \<C-w> and then 's' for top and bottom and 'v' for left and right. I can then open files in each pane with ":e file", close them with ":q" and such and switch back and forth between the panes with \<C-w> hjkl. This does not work in the NeoVintageous plugin but should be possible, or at least some limited number of configurations should be, because sublime text has the relevant arrangements in View>Layout.

**Comment by worldwalker2000** [comment]
Ok I have just realized that \<C-w> hjkl work for moving between the pains but I would still like to see \<C-W> s and v for splitting.

**Comment by gerardroche** [comment]
You will need to install Origami for window splitting: https://packagecontrol.io/packages/Origami.

See `help nv`

```

OPENING A VIEW                                               *nv-opening-view*

Some windowing commands require the Origami package.

See: https://packagecontrol.io/packages/Origami.

CTRL-W CTRL-S
CTRL-W s
CTRL-W S
:sp[lit] [file]         Split current window in two. The result is two views
                        on the same file. See|CTRL-W_s|for more details.

CTRL-W CTRL-V
CTRL-W v
CTRL-W V
:vs[plit] [file]        Like|:split|but split vertically. See|CTRL-W_v|.

```

Also here  are some custom mappings I use with Origami commands:

```
" Plugin: Origami: https://packagecontrol.io/packages/Origami.
nnoremap <leader>. :ToggleZoomPane fraction=0.98<CR>
nnoremap <leader>wd :DestroyPane direction=self<CR>
nnoremap <leader>ws :CarryFileToPane direction=down<CR>
nnoremap <leader>wv :CarryFileToPane direction=right<CR>
``

See `help nv` and https://blog.gerardroche.com/

**Comment by sourcevault** [comment]
Hi @gerardroche, could you provide some more info regarding origami and `neoVintageous` integration.

in Vanilla Origami, you  are supposed to use `Ctrl+k` but in `vim` the practice seems to be to use `Ctrl+w`.

I personally remapped `Ctrl+k` to `Ctrl+I` so now I do not know how to integrate both your helpful new commands and the original Origami ones.


This plugin has a more varied shortcut listing :

https://github.com/rodcloutier/Vintageous-Origami

can it be replicated in `neoVintageous` ?

**Comment by gerardroche** [comment]
Wow, thanks. I don't think I've sever seen the Vintageous Origami plugin before.

Origami is used for things like window splitting in NeoVintageous because it was easier to use the Origami commands than for me to spend the time reimplementing the functionality. For example `<C-w>s` (split horizontally) and `<C-w>v` (split vertically) will only work properly in Neo if you already have Origami installed. Note that you also need the control keys enabled too.

You can create your own mappings directly to the Origami commands. Here is one I use which maps `<leader>.` to the toggle zoom, very useful when you have many view groups open and you want to focus on the current view:

```
nnoremap <leader>. :ToggleZoomPane fraction=0.98<CR>
```

You can map to whatever you like, here the same thing is mapped to `<Cw>z`:

```
nnoremap <C-w>z :ToggleZoomPane fraction=0.98<CR>
```

I wrote a blog post with some usage examples:  https://blog.gerardroche.com/2022/11/21/vimrc-and-neovintageousrc/

To find out what an Origami command and arguments are enable Sublime Text logging. To enable Sublime Text command and input logging run the following in the console:

```
sublime.log_commands(True)
sublime.log_input(True)
```

Now run an Origami command and inspect the console. You can then use that information to create your mappings.

**Comment by sourcevault** [comment]
so in your example:
⤷ https://blog.gerardroche.com/2022/11/21/vimrc-and-neovintageousrc/ 

﹋﹋﹋
Mapping directly to Sublime Text commands is supported too. Convert the command to mix-case. For example to map `<D-i>` to the `goto_symbol_in_project` command:

`
noremap <D-i> :GotoSymbolInProject<CR>
`
﹏﹏﹏

▣ So if I understand you correctly, you have to take the sublime text command ( snake case ) and turn it Pascal case ( upper camel case ) ?

`goto_symbol_in_project -> :GotoSymbolInProject`


▣ Taking the example from Vintageous Origami, there is a command:

`K: Exchange with up pane`

This would take **two** origami command, can that be done in the `.neovintageousrc` file ?

Thank you for your input 😃, it would be nice to see screencasts showing all the details of using NeoVintageous.

**Comment by sourcevault** [comment]
https://github.com/NeoVintageous/NeoVintageous/assets/20347647/1a295923-bb57-448a-b49e-32c0710893d2

**Comment by gerardroche** [comment]
@sourcevault There is limited support for chaining commands. Try `<Bar>` instead of `\|`:

I haven't tested but I think this should work:

```
nnoremap <leader>ox<up> :TravelToPane direction=up<Bar>:ZoomPane fraction=0.90<CR>
```

An alternative is to create your own custom command that encapsulates the two commands. See https://blog.gerardroche.com/2017/11/01/neovintageous-1.4.0/ for a basic example mapping to custom user commands. Also keep an eye on the blog, there will be post shortly about this exact feature.
