### ISSUE TITLE
Bug: German `ü` and `ß` aren't accepted as key

### ISSUE THREAD

**Issue by chrisgrieser** [NeoVintageous/NeoVintageous#821]
**Describe the bug**  
The German letters `ü` and `ß` aren't registered at all when in normal mode.  By default, it does nothing, but just like any key, it can be mapped to something in `.neovintageousrc`. Other German special characters like `ä` work flawlessly, the `ö` is somewhat sketchy and seems to only work with some remappings, but not with others.

**To Reproduce**  
1. Switch to a German keyboard layout
2. Add the following to `.neovintageousrc`:

```vim
nnoremap ü j
nnoremap ß j
nnoremap ä j
nnoremap ö j
```

3. Reload rc file. 
4. try out the four keys. (in my case, only ä and ö work)

**Expected behavior**  
All German special characters should work. They do work in vim and other vim emulators.

**Actual behavior**  
They do not work.

**Versions**  
Show the Sublime Text console log: `Menu > View > Show Console`. 
Example: `startup, version: 3200 linux x64 channel: stable`

**Additional Information**  

```
startup, version: 4126 osx arm64 channel: stable
```

In the console with all the logging enabled, pressing the respective keys only results in this:

```log
chr evt: ü (0xfc)
chr evt: ß (0xdf)
```

---

btw, thank for for this excellent plugin. Feels like a real breeze otherwise!

**Comment by chrisgrieser** [comment]
oh thank you. Didn't expect it to be that straightforward. I made a brief one-line-PR to add the uppercase version of `ü` as well.

**Comment by sourcevault** [comment]
Trying to add support for Cyrillic letters, what do ❓ 😕

https://github.com/NeoVintageous/NeoVintageous/assets/20347647/851fb599-f741-408d-b256-11c2c8f292ca

**Comment by gerardroche** [comment]
@sourcevault Make sure you reload your rc file. Use the command palette to reload it.

**Comment by sourcevault** [comment]
https://github.com/NeoVintageous/NeoVintageous/assets/20347647/1d445d10-f5f3-4087-ac47-9f11a2d315e9

remapping only seems to work for single characters, unable to remap longer commands in command mode, example :

```
nnoremap дд dd
nnoremap чиш ciw
```

https://github.com/NeoVintageous/NeoVintageous/issues/276#issuecomment-318420349

⤷  In the case of non-english / non-latin keyboard I am aware their exists setups ( vim-xkbswitch 👀 ) that **only** switches to non-english layout in insert mode, and that system has some advantages over remapping it with `.neovintageousrc` 

**But** implementation wise, this would be way more reliable :

◻ you do not need to remap all normal mode commands, as it's unlikely there are people using non-english keyboards to write actual code,  I ran a character frequency count for javascript source; french and cyrillic symbols showed up only in comments, not in actual code, it could be different in other ecosystems, for example in the Julia programming world they use greek symbols within code.

◻ in case you **really** do need all possible vim commands in normal mode, you could build it up as you go, the only minor issue I see here is that your `.neovintageous` file will get really long.

◻ IMHO it's not a great idea to strongly couple the low level keyboard concerns to the high level vim semantics, switching keyboard layout in insert mode requires strong coupling between things that should work independently, in my case I do not even use the operating system to switch keyboards, and I might not be the only one.

**Comment by gerardroche** [comment]
NeoVintageous doesn't have any i18n support so you're going to run into all sorts of problems on top of the existing limitations. I'm wondering thought, because you're trying to solve i18n issues, if it would be better for you to do the remappings at the keymaps level instead of the neovintageousrc level.


For example, instead of `nnoremap дд dd` you would remap it at the keymaps level:

```
    {"keys": ["д"],         "command": "nv_feed_key", "args": {"key": "d"},        "context": [{"key": "vi_command_mode_aware"}]},
```

You then don't need `nnoremap дд dd` at all. NeoVintageous internally sees `d` when you press `д` so it should work when do `дд` because it sees `dd` internally.

I haven't tested this yet, but it would seem to me that we could go some ways towards supporting non-english layouts by creating keymaps translations. 

The non-english layouts issue is a little different that keyboard layout issues like support for Colemak and Dvorak layouts. I'm currently experimenting with those here 

https://github.com/gerardroche/NeoVintageousColemak 
https://github.com/gerardroche/NeoVintageousDvorak

My idea is to provide separate packages with mappings that are loaded before the user rc file.

I'm think the along the same lines for non-english translation keymaps. Seperate packages for each language. They would define all the keymap translations.

**Comment by sourcevault** [comment]
https://github.com/NeoVintageous/NeoVintageous/assets/20347647/af6ecf0e-ee80-459c-957b-70c4bde05d50

https://github.com/gerardroche/NeoVintageousColemak
https://github.com/gerardroche/NeoVintageousDvorak

I am aware of both these projects.
Out of curiosity do you personally use Colemak or Dvorak ?

https://github.com/sourcevault/FRU_68/blob/main/layout.png

This is my current layout `FRU_68` but it only work for Kinesis Advantage (and the software only works for windows, so not much help when it comes to universality), it may help in clarifying how to best approach the issue when it comes to NeoVintageous; as to take into account:

◼ the diversity of layout designs.

◼ language combinations. 

◼ varied software stack for emitting symbols.

Just changing your sublime keybinding is much simpler than using something like vim-xkbswitch.

**Comment by gerardroche** [comment]
Yes. That's what I thought. Remapping the keymaps for translations is cleaner. NeoVintageous just works the same internally because the translation is done before NeoVintageous receives the key aa input.

Now I'm thinking that there may be some confusion for the user at the rc file mapping level.

For example, if you map **в → d** and **ц → w** at the keymap level everything
should work fine, except if you then try map at the rc file level

For example, for arguments save let's say we to remap **d →  w**:

```vim
noremap в → ц
```

obviously this won't work because NeoVintageous won't know what **ц** is at the
rc file level, because the translation happens at the keymaps level. You would
have do:

```vim
noremap d w
```

This will obviously be confusing for users. That said, once you understand this
limitation it's not so bad.  One possible solution is to provide an rc
translation map alongside the keymaps translations so the user could in fact do:

```vim
noremap в → ц
```

Internally NeoVintageous would simply translate the right hand side using the
translation map i.e. `ц → w` hence `в` remaps to `w` internally.

So each translation package would consist of:

1. a keymaps translations
2. a hash map of the same translations for the rc file

I think that that might do it. Or least get us a workable solution.

P.S. No I don't use Colmak or Dvorak. I've just been testing them to see if I
could make a workable solution for those who do use them. It looks like they
might workable. I'm going implement a way to enable them, make them available
in Package Control, and then see what the feedback is. There maay be some users
out there that will be happy with them.

**Comment by eugenesvk** [comment]
> Trying to add support for Cyrillic letters, what do ❓ 😕

You can use this fork that has a command to auto-generate the full non-latin keybind for you from your config, and then you can freely use those non-latin keys in neovintageous config

https://github.com/eugenesvk/NeoVintageous/

It also handles ⇧4 messing your ; keybind

(unfortunately, the corresponding PR was rejected, so i18n is going to continue be painful https://github.com/NeoVintageous/NeoVintageous/pull/869)
