### ISSUE TITLE
FR: Option to add the current mode to the titlebar (= Compatibility with external apps)

### ISSUE THREAD

**Issue by chrisgrieser** [NeoVintageous/NeoVintageous#831]
Right now, the current mode is only displayed in the status bar (and via cursor shape). I am proposing to add it to the titlebar as well, since the window title is something many apps can access. This would mean that external apps could determine whether Sublime is in normal or insert mode. One relevant use case are text expanding apps, which could be disabled while in normal mode to avoid accidental triggering.

**Comment by gerardroche** [comment]
I don't think ST plugins can set or update the window title. I'm not aware of any support to be able to do that.

**Comment by gerardroche** [comment]
I'm going to close because as far as I'm aware there is no way API to implement this in Sublime. A theme can control the title bar but there is no way to programmatically update it on mode change. 

What would be really cool too is to be able to add colour in status bar, for example change the background colour of status bar based on the mode.

In vim airline the mode stands out nicely:

![Screenshot from 2022-09-25 07-53-48](https://user-images.githubusercontent.com/44148/192131940-c75fa2ea-29c4-40ba-862c-4fb810859ee1.png)

![Screenshot from 2022-09-25 07-53-25](https://user-images.githubusercontent.com/44148/192131938-11e40b43-0751-41e1-884d-58ef283d8f2c.png)
![Screenshot from 2022-09-25 07-53-38](https://user-images.githubusercontent.com/44148/192131939-bedb90a6-4550-41f0-b9a8-ef46285a4dd1.png)
