### ISSUE TITLE
Some binding wont work

### ISSUE THREAD

**Issue by NEX-S** [NeoVintageous/NeoVintageous#836]
**Describe the bug**  
Some binding wont work

```vim
nnoremap <S-TAB> <C-n>
inoremap <A-j> <C-n>
inoremap <A-k> <C-p>

nnoremap < <<
vnoremap < <gv

nnoremap dp "dp

etc
```

**Versions**  
`version: 4126 linux x64`

**Comment by gerardroche** [comment]
The indent ones will work using `<lt>` instead of `<`

```

nnoremap <lt> <lt><lt>
vnoremap <lt> <lt>gv
```


Only a few `inoremap` keys are currently supported: `<Esc>`, `<C-[>`, `<C-l>`, `<C-c>`, `<C-w>`, `<C-x>`, `<C-u>`. I opened an issue to add more: https://github.com/NeoVintageous/NeoVintageous/issues/837

`Shift-tab` is currently not supported, but will be soon. https://github.com/NeoVintageous/NeoVintageous/issues/838 

`nnoremap dp "dp` should work but it breaks all other commands starting with `d` so it's not really supported. I think vim allows you to define it without messing up the other commands.

**Comment by gerardroche** [comment]
```
"keys": ["g", "d"],
```

This is a multi key binding meaning when you press `g` Sublime Text waits for your next key. These kind of keybindings will cause conflicts with neovintageous bindings and will break the commands that start with the first key, in this case `g`.

The way to deal with this is with a custom mapping in your rc file, you can map Sublime Text commands using the format the command name as MixedCase, here I map to the ST `show_overlay` command with `<leader>gf`:

```
nnoremap <leader>gd :LspSymbolDefinition side_by_side=false force_group=true fallback=true<CR>
```

This will invoke lsp `command: lsp_symbol_definition {"fallback": true, "force_group": true, "side_by_side": false}`

See https://github.com/NeoVintageous/NeoVintageous/blob/master/res/doc/neovintageous.txt#L144 for details on mapping custom commands.

Nv currently doesn't support context in mappings, there is an open issue https://github.com/NeoVintageous/NeoVintageous/issues/643


`CTRL-w CTRL-w` is not currently support, I opened an issue for it here https://github.com/NeoVintageous/NeoVintageous/issues/839

**Comment by gerardroche** [comment]
`<C-w>b` is close to the functionality of `<C-w>w`

**Comment by gerardroche** [comment]
`gf` should work without the mapping `nnoremap gf :ViOpenFileUnderSelection<CR>`

**Comment by gerardroche** [comment]
> and <A-...> wont working when menu is on.

Take at a look at the `winaltkeys` options, by default it's set to `menu` meaning if you have the menu turned on, then the alt keys related to the menu will invoke the menu, otherwise they get sent to the mapping handler. If you set `winaltkeys` to **no** then they always go to the mapping handler, and if **yes** then they never get sent to the mapping handler.  

See `:h nv-options`.

```
						*'winaltkeys'* *'wak'*
'winaltkeys' 'wak'	string	(default "menu")
			global
			{only used in Win32}
	Some GUI versions allow the access to menu entries by using the ALT
	key in combination with a character that appears underlined in the
	menu.  This conflicts with the use of the ALT key for mappings and
	entering special characters.  This option tells what to do:
	  no	Don't use ALT keys for menus.  ALT key combinations can be
		mapped, but there is no automatic handling.
	  yes	ALT key handling is done by the windowing system.  ALT key
		combinations cannot be mapped.
	  menu	Using ALT in combination with a character that is a menu
		shortcut key, will be handled by the windowing system.  Other
		keys can be mapped.
```

**Comment by gerardroche** [comment]
To jump back and forward try `<C-i>` (in), `<C-o>` out

**Comment by gerardroche** [comment]
I can't see much different in lag between the jump forward and back commands.
