### ISSUE TITLE
visual block mode ) -> using arrow wont scroll the document view

### ISSUE THREAD

**Issue by huyhoang8398** [NeoVintageous/NeoVintageous#887]
**Describe the bug**  
ctrl + v ( visual block mode ) -> using arrow wont scroll the document view
**To Reproduce**  
1. Open any long file
2. Use ctrl +v (visual block mode)
3. use up/down arrow to reach end of file or longer than a page
4. page doenst scroll

**Expected behavior**  
page scroll

**Actual behavior**  
page not scroll 

**Versions**  
Show the Sublime Text console log: `Menu → View → Show Console`.
Example: `startup, version: 3200 linux x64 channel: stable`
![image](https://github.com/NeoVintageous/NeoVintageous/assets/25379882/0c93ae09-5a1e-4551-97d7-61a91901eab0)

**Comment by gerardroche** [comment]
What do you mean by "page doesn't scroll"?

When you move the cursor in visual mode it does not scroll by page, it scrolls
by line.

If you want to show context as you scroll, use the Sublime Text setting.

Menu → Preferences → Settings

```
"scroll_context_lines": 8,
```

To scroll by page use CTRL-d and CTRL-u.  Now, I've just noticed that CTRL-d and
CTRL-u doesn't workin visual block mode, so that's a bug. But you can see how it
is supposed to work in visual mode.

**Comment by huyhoang8398** [comment]
Sorry for my english.
I made a video to show you the bug.
When im in visual mode, you can see my cursor is way above the page, but i cannot see it 


https://github.com/NeoVintageous/NeoVintageous/assets/25379882/b068270f-2c8f-43d7-be43-1ab1732b810f

**Comment by gerardroche** [comment]
It looks like it starts to move, but then stops. It starts to move from line 40
to 35, but then stops.

Does the same happen with other visual modes like characterwise `v` and linewise `V`?

**Comment by gerardroche** [comment]
Yes, I can reproduce it. It only seems to effect going up for me.

**Comment by huyhoang8398** [comment]
for me both go up and down, 
Also I cannot use for example, in visual block mode ( use gg to go to top, or G to go bottom ) should i make a separate issue?

**Comment by huyhoang8398** [comment]
> It looks like it starts to move, but then stops. It starts to move from line 40 to 35, but then stops.
> 
> Does the same happen with other visual modes like characterwise `v` and linewise `V`?

no, only in visual block, normal visual mode works fine

**Comment by huyhoang8398** [comment]
> It looks like it starts to move, but then stops. It starts to move from line 40 to 35, but then stops.
> 
> Does the same happen with other visual modes like characterwise `v` and linewise `V`?

no it's actually can move to more than 40, just the text window doesnt scroll ( following the cursor , cursor moved out of the work area)

**Comment by gerardroche** [comment]
Yes, open separate issues for commands that are not implemented for visual block
mode. For example, visual block mode is not yet implemented for gg and G.

I think commands like that will be easy to add for visual block mode. Some
commands like CTRL-d and CTRL-u are much harder because there are lots of edge
cases with those commands.
